### ISSUE TITLE
Micromamba applies pip `--install-option` to all pip packages

### ISSUE THREAD

**Issue by gjoseph92** [mamba-org/mamba#1005]
It appears that when installing from an `environment.yml` file with micromamba that contains a `pip` section, micromamba simply concatenates all the dependencies and passes them as arguments to `pip install`. This causes issues for pip dependencies that use the individual-requirement-specific flags `--install-option`, `--global-option` or `--hash` ([pip docs](https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format)).

For example, I was trying to install this:
```yaml
name: base
channels:
  - conda-forge
dependencies:
  - python=3.9.1
  - pip=21.1.1
  - compilers=1.1.3
  - Cython=0.29.22
  - git
  - pip:
      - git+https://github.com/dask/dask.git@main
      - git+https://github.com/dask/distributed.git@main --install-option="--with-cython=profile"
```

I get an error like:
```
Installing collected packages: toolz, locket, pyyaml, partd, heapdict, fsspec, cloudpickle, zict, tornado, tblib, sortedcontainers, psutil, msgpack, dask, click, distributed
    Running setup.py install for toolz ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fdk727mx/toolz_d2a4088f67394b2e95aee3e74df346db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fdk727mx/toolz_d2a4088f67394b2e95aee3e74df346db/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bpj7hd4i/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.9/toolz '"--with-cython=profile"'
         cwd: /tmp/pip-install-fdk727mx/toolz_d2a4088f67394b2e95aee3e74df346db/
    Complete output (1 lines):
    invalid command name '"--with-cython=profile"'
```
Because the `setup.py` for the `toolz` package doesn't know what to do with this `--with-cython=profile` option, which is a special option intended only for `distributed.git@main` (which knows what to do with it), installation fails.

However, using mamba (or conda) with this same file works fine. AFAIK, conda's strategy is to write the pip dependencies out to a temporary `requirements.txt` file, then pip-install that. Since each dependency ends up on its own line in the `requirements.txt`, pip understands that the `--install-option` only applies to that line. Perhaps micromamba could take a similar approach?

cc @wolfv since this seems related to #885/#589
