### ISSUE TITLE
mamba create error report

### ISSUE THREAD

**Issue by k1m190r** [mamba-org/mamba#1058]
Situation:
"Direct" connection via ZScaler Client Connector (meaning no proxy) results in following error:

    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "c:\Apps\mambaforge\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "c:\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 898, in exception_converter
        raise e
      File "c:\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 892, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "c:\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 851, in _wrapped_main
        result = do_call(args, p)
      File "c:\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 736, in do_call
        exit_code = create(args, parser)
      File "c:\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 640, in create
        return install(args, parser, "create")
      File "c:\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 515, in install
        index = load_channels(pool, channels, repos)
      File "c:\Apps\mambaforge\lib\site-packages\mamba\utils.py", line 100, in load_channels
        index = get_index(
      File "c:\Apps\mambaforge\lib\site-packages\mamba\utils.py", line 81, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: The process cannot access the file because it is being used by another process.
    : 'C:\Users\USER1\AppData\Local\Temp\mambafAbbTKMtUXf'

    `$ c:\Apps\mambaforge\Scripts\mamba create --name test1 python=3.8 -vvv -y`

Full -vvv log [here](https://gist.github.com/k1m190r/2e35b2c1963444611f440cb98f3f33f4).

Exactly the same prompt but with `conda` instead, results in no errors. Env gets created.:
`$ c:\Apps\mambaforge\Scripts\conda create --name test1 python=3.8 -vvv -y`

Connected to VPN with http/s proxies set, both mamba and conda work as expected with **no** errors.

Package dirs cleaned between multiple tests:
`mamba clean --all -y --force-pkgs-dirs`

**Comment by wolfv** [comment]
Hi @k1m190r does this happen over a long period of time? Sometimes these issues clear up on the server side.

I found this issue in the curl issue tracker: https://github.com/curl/curl/issues/4427 which sounds this might be caused by some misconfiguration in the server. 

Can you try to download the file with curl itself (`curl https://..../../ -o test.json`)

Lastly, you posted the URL with your token inside. You should revoke that token asap :)

We need to implement token hiding in mamba #888

**Comment by k1m190r** [comment]
@wolfv curl produces no errors and downloads the file. 

I noticed a difference between logs for cases 
when it works 
```
* schannel: ALPN, offering http/1.1
* schannel: ALPN, server accepted to use http/1.1
```
and when it does not:
```
* schannel: ALPN, offering http/1.1
* ALPN, server did not agree to a protocol
```

Sorry I'm not sure I understood the token bit :). Which line is it on and how do I revoke it?

**Comment by wolfv** [comment]
this line:

https://conda.anaconda.org/t/bi-90f4987e-2968-45da-be84-5489ed301a9f/conda-forge/win-64/repodata.json

contains your token (after `/t/....`)

Does it work when the token is not in your URL?

**Comment by wolfv** [comment]
note these tokens are stored in a location like `~/.continuum/anaconda-client/tokens/...`

**Comment by k1m190r** [comment]
I see that for the case of `conda-forge/noarch/repodata.json` token is present and download worked:

```
INFO    Transfer done ...
INFO    Transfer finalized, status: 200 [https://conda.anaconda.org/t/bi-90f4987e-2968-45da-be84-5489ed301a9f/conda-forge/noarch/repodata.json] 5500793 bytes
INFO    HTTP response code: 200
INFO    Finalized transfer: https://conda.anaconda.org/t/bi-90f4987e-2968-45da-be84-5489ed301a9f/conda-forge/noarch/repodata.json
```
With or without token curl-ing manually works, for files...


Does this python error from the log hints towards a problem?
or its a consequence of the curl failing to download?
```
 File "c:\Apps\mambaforge\lib\site-packages\mamba\utils.py", line 81, in get_index
    is_downloaded = dlist.download(True)
RuntimeError: The process cannot access the file because it is being used by another process.
: 'C:\Users\USER1\AppData\Local\Temp\mambafAbbTKMtUXf'
```

**Comment by crusaderky** [comment]
This exact error is happening to me as well, fairly frequently - so far, 3 times out of 180 runs. All on Windows.
I'm running on github actions:

```yaml
jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          environment-file: continuous_integration/environment-${{ matrix.python-version }}.yaml
```
``mamba list`` reports ~230 packages - which likely increases the chance of race conditions.
