### ISSUE TITLE
Mamba does'nt find a solution when mixing conda-forge/defaults and not specifying Python explicitely

### ISSUE THREAD

**Issue by jolos** [mamba-org/mamba#1102]
on mamba >= 0.15 the following environment file (adapted from the quetz repo) fails to find a solution and progress to installation of the packages

```yaml
name: quetz
channels:
  - defaults
  - https://repo.mamba.pm/conda-forge
dependencies:
  #- python>=3.7
  - pip
  - fastapi
  - typer
  - authlib
  - psycopg2
  - httpx=0.16.0
  - sqlalchemy<1.4.0
  - sqlalchemy-utils
  - sqlite
  - python-multipart
  - uvicorn
  - zstandard
  - conda-build
  - appdirs
  - toml
  - quetz-client
  - fsspec
  - requests
  - h2<4.0.0
  - pluggy
  - jinja2
  - itsdangerous
  - alembic
  - zchunk
  - s3fs
  - sphinx
  - sphinx-book-theme
  - tenacity
  - xattr
  - aiofiles
  - pyyaml
  - ujson
  - prometheus_client
  - pamela
  - typing_extensions
  - adlfs
  ```
  
Any of the following actions resolves the issue

- removing the defaults channel
- uncommenting the python requirement
- downgrading to mamba 0.14
- reducing the number of requirements in the file.
