### ISSUE TITLE
Mamba(0.15.3) chose an incorrect channel when specifying the channel.

### ISSUE THREAD

**Issue by yanpd01** [mamba-org/mamba#1135]
First, I create a multi-channel called qinghua in .condarc file and I will paste the content in .condarc at the end.

When I run `mamba install blast -c qinghua` with mamba(0.15.3), it works incorrectly with showing:
Looking for: ['blast']
pkgs/main/noarch         [====================] (00m:00s) No change
qinghua/linux-64         [====================] (00m:00s) No change
qinghua/noarch           [====================] (00m:00s) No change
bioconda/linux-64        [====================] (00m:00s) No change
bioconda/noarch          [====================] (00m:00s) No change 
......
The channel named qinghua/linux-64 is incorrect.

When I run `mamba install blast -c qinghua` with mamba(0.14.1), it works properly with showing:
Looking for: ['blast']
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
bioconda/linux-64        Using cache
bioconda/noarch          Using cache
anaconda/pkgs/msys2/linu [====================] (00m:00s) Done
anaconda/pkgs/r/noarch   [====================] (00m:00s) Done
anaconda/cloud/menpo/noa [====================] (00m:00s) Done
anaconda/cloud/pytorch/n [====================] (00m:00s) Done
anaconda/cloud/simpleitk [====================] (00m:00s) Done
anaconda/pkgs/main/noarc [====================] (00m:00s) Done
anaconda/pkgs/r/linux-64 [====================] (00m:01s) Done
anaconda/cloud/menpo/lin [====================] (00m:00s) Done
anaconda/cloud/simpleitk [====================] (00m:00s) Done
......
It works well, the channel named anaconda/\*/\* is the channels specified in .condarc.

This is the content in .condarc.
```
## option --------------------------------------------------------
auto_activate_base: false
show_channel_urls: true
report_errors: true

## channels ------------------------------------------------------
channels:
  - defaults

## default_channels ----------------------------------------------
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - bioconda

## custom_multichannels ------------------------------------------
custom_multichannels:
  condayuan:
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
    - conda-forge
    - bioconda
    - qiime2
    - r
  qinghua:
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/qiime2
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/simpleitk

```
