### ISSUE TITLE
`micromamba` `--json` pip doesnt guarentee json output

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/mamba#1181]
I'm trying to use micromamba to solve a specific environment. I'm using `micromamba create --dry-run` for that. Is there a better way?

This works pretty well but when running:

```
micromamba create --dry-run -f environment.yml -n test --json
```

with a pip package in the environment 

```yaml
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - pytool
```

the command outputs json and the following: 

```
Installing pip packages: pytool
ERROR   No such file or directory
```

I would expect the output to only be in json format.
