### ISSUE TITLE
mamba installs PyTorch CPU version instead of the CUDA version

### ISSUE THREAD

**Issue by bryant1410** [mamba-org/mamba#1349]
Given this `environment.yml` file:

```yaml
name: test
channels:
  - pytorch
dependencies:
  - tensorflow=2.5.0
  - six=1.15.0
  - regex=2021.7.6
  - numpy
  - pytorch=1.8.1
  - nltk=3.6.2
  - cudatoolkit=10.2
  - python=3.9
  - sentencepiece
```

`mamba env create` installs the CPU version of PyTorch (`py3.9_cpu_0`) but the CUDA one should be installed instead.

I'm using mamba 0.19.1 and conda 4.11.0 on Linux.
