### ISSUE TITLE
`activate` is not a subcommand of `micromamba`

### ISSUE THREAD

**Issue by igaloly** [mamba-org/mamba#1359]
When I run `bin/micromamba activate my-custom-env`, micromamba raises an error that `activate` and `my-custom-env` are not expected subcommands.
This is an image of the `bin/micromamba --help`. It is possible to see that indeed `activate` is not listed in the subcommands list.
I would appreciate any help with this :)
![image](https://user-images.githubusercontent.com/38460810/146510789-ff9486f8-3d62-41d3-9eff-128a9353c574.png)

**Comment by maresb** [comment]
Hi @igaloly, this seems to be a duplicate of #1323.

As suggested in the image, does the activate command work after running `eval "$(micromamba shell hook -s bash)"`?

**Comment by igaloly** [comment]
Hi @maresb , thanks for the quick reply.
Unfortunately, your suggestion does not work.

My code runs as a Github action. This is the workflow YAML:
```
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install dependencies
        run: make install-deps

      - name: Test
        run: make test
```

When `install-deps` contains:
```
	@echo [!] Installing Semver
	@sudo wget https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver -O /usr/bin/semver
	@sudo chmod +x /usr/bin/semver

	@echo [!] Installing yq
	@sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

	@echo [!] Installing mamba
	@sudo wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
```

And `test` is built of 3 functions: `install-base-env` `install-test-environment` and `run-tests`.

While `install-base-env` contains:
```
	@echo [!] Init micromamba shell
	@eval "$(micromamba shell hook -s bash)"

	@echo [!] Creating base env
	@bin/micromamba create -n base-env -f base-env.yaml

	@echo [!] Activating base env
	@bin/micromamba activate base-env
```

`install-test-environment` contains:
```
	@echo [!] Extending base environment with test dependencies
	@bin/micromamba update -n base-env --file test-env.yaml
```

And `run-tests` contains:
```
	@echo [!] Run tests
	@bin/micromamba run pytest -s --disable-warnings
```

**Comment by igaloly** [comment]
@maresb BTW, i also tried using `mamba-org/provision-with-micromamba` without success.
`The following arguments were not expected: base-env activate`

**Comment by maresb** [comment]
@igaloly, I'd try removing `bin/` from before the `micromamba` command. The reason is that the shell hook overrides the `bin/micromamba` binary by defining a Bash function `micromamba()` which handles the activation.

The logic is that Bash executes all binaries as subprocesses, but activation entails modifying the active shell. Subprocesses can't modify their parent shells, so we overload `micromamba` with a Bash function which can.

When you run `micromamba activate`, the bash function `micromamba()` intercepts this and activates the environment. When you run `micromamba somethingelse`, the bash function calls `bin/micromamba somethingelse`.

When you run `bin/micromamba activate`, that bypasses the shell function, producing the error you see.

I don't know anything about https://github.com/mamba-org/provision-with-micromamba, so if you're having an issue I suggest reporting it there.

**Comment by igaloly** [comment]
@maresb , Unfortunately, when I remove `bin/` the `micromamba` command is not found.
I assume that this is because I try to run it from a `Makefile`, which executes each line in a new shell.
I did manage to achieve my end goal (run `pytest`) using `provision-with-micromamba` like so:
```
      - name: Install Mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: base-env.yaml
          environment-name: base-env

      - name: Test
        shell: bash -l {0}
        run: |
          micromamba update -n base-env -f test-env.yaml
          pytest -s --disable-warnings
```

I still much prefer using the `Makefile` function for this action.
I would love to hear your and @wolfv ideas on how to make it work :)
