### ISSUE TITLE
solver_addrule: Assertion `!p2 && d > 0' failed.

### ISSUE THREAD

**Issue by Hoeze** [mamba-org/mamba#1382]
I just tried creating a new environment from the following file:

<details>

```yaml
name: newenv
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  - argcomplete
  - autoconf
  - automake
  - aws-sdk-cpp
  - babel
  - backports
    #  - backports.functools_lru_cache
    #  - backports.lzma
  - bcftools
  - bcrypt
  - bedtools
  - bfg
  - biopython
  - bioservices
  - black
  - blake3
  - bleach
  - blessings
  - blinker
  - blosc
  - bokeh
  - boost-cpp
  - bottleneck
  - brotli
  - bump2version
  - bz2file
  - bzip2
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - cachey
  - click
  - cloudpickle
  - cmake
  - configparser
  - cookiecutter
  - coreutils
  - coverage
  - cudatoolkit-dev
  - cudnn
  - curl
  - cython
  - cyvcf2
  - dask
  - dask-glm
  - dask-ml
  - dask-xgboost
  - datrie
  - dill
  - distributed
  - dm-tree
  - fastavro
  - fastparquet
  - filprofiler
  - fisher
  - fsspec
  - gitpython
  - glmnet
  - glow
  - google-cloud-storage
  - gradle
  - graphite2
  - graphviz
  - gsutil
  - gtfparse
  - h5netcdf
  - h5py
  - hdf5
  - holoviews
  - htslib
  - humanfriendly
  - hvplot
  - hyperopt
  - hypothesis
    #  - ibis-framework
  - imagemagick
    #  - intake
    #  - intake-xarray
  - ipydatawidgets
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jinja2-time
  - joblib
  - jupytext
  - keras
  - kiwisolver
  - lightgbm
  - line_profiler
  - markdown
  - matplotlib
  - matplotlib-venn
  - maven
  - memory_profiler
  - mlflow
  - mlxtend
  - mock
  - modin
  - mongodb
  - natsort
  - nb_conda_kernels
  - nbconvert
  - ncls
  - networkx
  - numba
  - numexpr
  - numpy
  - numpydoc
  - optuna
  - orc
  - pandas
  - pandera
  - pandoc
  - pandocfilters
  - papermill
  - patsy
  - perl
  - pip
  - plotly
  - plotly-orca
  - plotnine
  - postgresql
  - psutil
  - psycopg2
  - pyarrow
  - pyfaidx
  - pyranges
  - pyspark=3.1.2
  - pytest
  - pytest-cov
  - python
  - python-rocksdb
  - python-snappy
  - pyyaml
  - rocksdb
  - samtools
  - scikit-allel
  - scikit-image
  - scikit-learn[version='>0.24.2']
  - scipy
  - seaborn
  - setuptools
  - setuptools-scm
  - shap
  - snakemake[version='<6.8']
  - snappy
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlalchemy
  - sqlite
  - sqlparse
  - statsmodels
  - tensorboard
  - tensorboardx
  - tensorflow
  - tensorflow-estimator
  - toml
  - toolz
  - tqdm
    #  - vaex
    #- vaex-astro
    #- vaex-core
    #- vaex-hdf5
    #- vaex-jupyter
    #- vaex-ml
    #- vaex-server
    #- vaex-viz
  - vt
  - wget
  - wheel
  - xarray
  - xeus
  - xeus-python
  - xgboost
  - yaml
  - zarr
  - zstd
```

</details>

Result after computing a while:

`mamba env create -f newenv.env.yaml --name newenv "python=3.9"`
```
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
bioconda/linux-64        Using cache
bioconda/noarch          Using cache
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
plotly/noarch            [====================] (00m:00s) No change
plotly/linux-64          [====================] (00m:00s) No change


Looking for: ['argcomplete', 'autoconf', 'automake', 'aws-sdk-cpp', 'babel', 'backports', 'bcftools', 'bcrypt', 'bedtools', 'bfg', 'biopython', 'bioservices', 'black', 'blake3', 'bleach', 'blessings', 'blinker', 'blosc', 'bokeh', 'boost-cpp', 'bottleneck', 'brotli', 'bump2version', 'bz2file', 'bzip2', 'ca-certificates', 'cached-property', 'cached_property', 'cachetools', 'cachey', 'click', 'cloudpickle', 'cmake', 'configparser', 'cookiecutter', 'coreutils', 'coverage', 'cudatoolkit-dev', 'cudnn', 'curl', 'cython', 'cyvcf2', 'dask', 'dask-glm', 'dask-ml', 'dask-xgboost', 'datrie', 'dill', 'distributed', 'dm-tree', 'fastavro', 'fastparquet', 'filprofiler', 'fisher', 'fsspec', 'gitpython', 'glmnet', 'glow', 'google-cloud-storage', 'gradle', 'graphite2', 'graphviz', 'gsutil', 'gtfparse', 'h5netcdf', 'h5py', 'hdf5', 'holoviews', 'htslib', 'humanfriendly', 'hvplot', 'hyperopt', 'hypothesis', 'imagemagick', 'ipydatawidgets', 'ipykernel', 'ipython', 'jedi', 'jinja2', 'jinja2-time', 'joblib', 'jupytext', 'keras', 'kiwisolver', 'lightgbm', 'line_profiler', 'markdown', 'matplotlib', 'matplotlib-venn', 'maven', 'memory_profiler', 'mlflow', 'mlxtend', 'mock', 'modin', 'mongodb', 'natsort', 'nb_conda_kernels', 'nbconvert', 'ncls', 'networkx', 'numba', 'numexpr', 'numpy', 'numpydoc', 'optuna', 'orc', 'pandas', 'pandera', 'pandoc', 'pandocfilters', 'papermill', 'patsy', 'perl', 'pip', 'plotly', 'plotly-orca', 'plotnine', 'postgresql', 'psutil', 'psycopg2', 'pyarrow', 'pyfaidx', 'pyranges', 'pyspark=3.1.2', 'pytest', 'pytest-cov', 'python', 'python-rocksdb', 'python-snappy', 'pyyaml', 'rocksdb', 'samtools', 'scikit-allel', 'scikit-image', "scikit-learn[version='>0.24.2']", 'scipy', 'seaborn', 'setuptools', 'setuptools-scm', 'shap', "snakemake[version='<6.8']", 'snappy', 'sphinx', 'sphinx-autodoc-typehints', 'sphinx_rtd_theme', 'sphinxcontrib-applehelp', 'sphinxcontrib-devhelp', 'sphinxcontrib-htmlhelp', 'sphinxcontrib-jsmath', 'sphinxcontrib-qthelp', 'sphinxcontrib-serializinghtml', 'sqlalchemy', 'sqlite', 'sqlparse', 'statsmodels', 'tensorboard', 'tensorboardx', 'tensorflow', 'tensorflow-estimator', 'toml', 'toolz', 'tqdm', 'vt', 'wget', 'wheel', 'xarray', 'xeus', 'xeus-python', 'xgboost', 'yaml', 'zarr', 'zstd']                                                 


python: /home/conda/feedstock_root/build_artifacts/libsolv_1625855492383/work/src/rules.c:261: solver_addrule: Assertion `!p2 && d > 0' failed.
[1]    2404215 abort (core dumped)  mamba env create -f newenv.env.yaml --name newenv "python=3.9"
```
