### ISSUE TITLE
Incorrect channel of packages on `mamba env update`

### ISSUE THREAD

**Issue by bryant1410** [mamba-org/mamba#1540]
I have the following `environment.yaml` file:

```yaml
name: test
dependencies:
  -              python
  -     pytorch::pytorch=1.10*=*cuda*
  - conda-forge::pytorch-lightning=1
  -     pytorch::torchvision
```

Everything goes well on `mamba env create`, but if I do `mamba env update` immediately after, some packages are substituted for `conda-forge` versions:

```



Transaction

  Prefix: /opt/conda/envs/test

  Updating specs:

   - python
   - pytorch::pytorch=1.10[build=*cuda*]
   - conda-forge::pytorch-lightning=1
   - pytorch::torchvision


  Package     Version  Build                        Channel                    Size
─────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────

  + cudnn    8.2.1.32  h86fa8c9_0                   conda-forge/linux-64     Cached
  + magma       2.5.4  h6103c52_2                   conda-forge/linux-64     Cached
  + nccl     2.11.4.1  h5c60f85_2                   conda-forge/linux-64     Cached
  + ninja      1.10.2  h4bd325d_1                   conda-forge/linux-64     Cached
  + sleef       3.5.1  h9b69904_2                   conda-forge/linux-64     Cached

  Change:
─────────────────────────────────────────────────────────────────────────────────────

  - pytorch    1.10.2  py3.9_cuda11.3_cudnn8.2.0_0  installed                      
  + pytorch    1.10.2  cuda112py39h4de5995_1        conda-forge/linux-64      667MB

  Summary:

  Install: 5 packages
  Change: 1 packages

  Total download: 667MB
```

Versions of mamba and Conda;

mamba 0.22.1
conda 4.11.0

**Comment by Alex-ley-scrub** [comment]
I have a very similar issue with mamba 0.25.0 & conda 4.13.0
I also have micromamba 0.25.1 and that shows the same behaviour as mamba (makes sense).

The weird thing is, I think it only started happening recently, and I didn't update mamba or micromamba. I've been using micromamba on EC2 linux service start-up scripts for speed and it has been working well until today.

My `environment.yml` looks like this:

```
name: py39
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - setuptools>=63.0
  - wheel>=0.37
  - numpy=1.23.1
  - pytorch=1.12.1
  - cudatoolkit=11.6
  - pycurl=7.44.1
  - libgcc=7.2.0
  - pyicu=2.7.4
  - pip>=21.0
```

If I do this command with conda it works as expected:
```sh
conda env update --prune -f environment.yml
```

if I do either of these it fails in a similar way (I tried a few different things to see if I could make it work like removing torch first before doing the update or using conda to do the update and then doing the mamba/micromamba update commands to see if I could coerce them to use the installed/cached versions of the packages but all failed):
```sh
mamba env update --prune -f environment.yml
micromamba update --prune -f environment.yml 
```
e.g.:
![image](https://user-images.githubusercontent.com/94057608/187918027-b62a7c6d-68f5-4043-8be5-5f23a8fae706.png)

or:
![image](https://user-images.githubusercontent.com/94057608/187918464-7f9793d5-7991-41bc-b77f-aa98d9050f07.png)

**Comment by Alex-ley-scrub** [comment]
@jonashaag do you know if there is any plan to change this behaviour anytime soon?

**Comment by gdevenyi** [comment]
Following this now because FSL has condaized its entire install, and they use this feature. Custom user/system configs break their install as a result.

**Comment by jjerphan** [comment]
This issue depends mostly on channels and and the channel priority which are used.

I would suggest making sure packages on the `nvidia` and `pytorch` channels (or any other custom one) have precedence over the ones on `conda-forge`.

On the command line, this would be for instance in case of installation:

```
micromamba
```

There are several ways to implement this policy, but the most convenient one is to adapt local configuration (e.g. `$CONDA_PREFIX/.condarc`) or global configurations (e.g. `$HOME/.condarc`).

For instance, adding this pieces of configuration:

```yaml
channel_priority: strict                                                                                                                                                                                                                       
channels:     
 - nvidia
 - pytorch                                                                                                                                                                                                                                   
 - conda-forge
```

would prevent update of packages from channels with lesser priority (here `conda-forge`) if those package are present in channel of greater priority (here `nvidia`); solving @bryant1410's original problem.

For background reading, I recommend [this section of conda's documentation on managing channels](https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-channels.html), especially [the subsection on strict channel priority](https://docs.conda.io/projects/conda/en/stable/user-guide/tasks/manage-channels.html#strict-channel-priority).

I am closing this issue as completed, but feel free to comment if something is unclear or if you still meet issues.
