### ISSUE TITLE
[micromamba] Environment created from explicit spec file for osx-arm64 not working

### ISSUE THREAD

**Issue by HedgehogCode** [mamba-org/mamba#1591]
If I create an environment from an explicit spec file for the __osx-arm64__ platform, Python in this environment does not work.

### System
* MacOS Monterey 12.2
* MacBookPro18,4, Apple M1 Max with 32GB Ram

### Steps to reproduce

1. Create an environment from this yaml (just a random example):
```yaml
name: my_env
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.8
- py4j
- pandas
- pyarrow
- python-dateutil
- numpy
- asammdf=5.19.14
```
Note: This environment works perfectly.

2. Generate an explicit environment lock file (`micromamba env export -e`). (My result: [specs_osx-arm64.txt](https://github.com/mamba-org/mamba/files/8340534/specs_osx-arm64.txt))

3. Create a new environment using the explicit file:
```
$ micromamba create -p ./my_env_clone -c conda-forge -f specs_osx-arm64.txt -r ./root-arm64
```
4. Activate the environment and try to run Python. Result: Python crashes immediately.
```
$ micromamba activate -p ./my_env_clone
$ python
[1]    44142 killed     python
```
Note: The `my_env` and `my_env_clone` environments contain the same files but the content of some files differs.
