### ISSUE TITLE
[micromamba] config show -s not working with maps with lists

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1640]
There is a bad_conversion error happening when using `micromamba config show -s` with a more complicated config such as:

```yaml
channels:
- conda-forge
custom_multichannels:
  conda-forge2:
    - conda-forge
```
