### ISSUE TITLE
Got file size doesn't match while using 3rd mirror

### ISSUE THREAD

**Issue by eromoe** [mamba-org/mamba#1766]
My .condarc : 
```
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

`mamba install -c conda-forge cvxpy` got error ,  by removed custom mirror got success

```
  Package              Version  Build                 Channel                                                                 Size
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  cvxpy                  1.2.1  py39h2804cbe_0        mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64      89 KB
  cvxpy-base             1.2.1  py39hd2dba81_0        mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64     920 KB
  ecos                  2.0.10  py39h20ef057_0        mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64      82 KB
  libblas                3.9.0  13_osxarm64_openblas  mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64      12 KB
  liblapack              3.9.0  13_osxarm64_openblas  mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64      12 KB
  osqp             0.6.2.post0  py39h7f752ed_3        mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64     173 KB
  qdldl-python           0.1.5  py39h7f752ed_2        mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64      93 KB
  scs                    3.2.0  py39h60687c9_0        mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64      80 KB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  ca-certificates  2022.5.18.1  h4653dfc_0            installed
  ca-certificates    2022.6.15  h4653dfc_0            mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64     149 KB
  certifi          2022.5.18.1  py39h2804cbe_0        installed
  certifi            2022.6.15  py39h2804cbe_0        mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64     155 KB
  libcxx                12.0.0  hf6beb65_1            installed
  libcxx                14.0.6  h04bba0f_0            mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64       1 MB
  openssl               1.1.1o  ha287fd2_0            installed
  openssl               1.1.1p  ha287fd2_0            mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64       2 MB

  Summary:

  Install: 8 packages
  Upgrade: 4 packages

  Total download: 5 MB

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] Y
ERROR   transaction.cpp:84 File not valid: file size doesn't match expectation "/Users/kasim/opt/anaconda3/pkgs/cvxpy-1.2.1-py39h2804cbe_0.tar.bz2"
cvxpy                    [====================] (00m:00s) Validating...
libc++abi: terminating with uncaught exception of type std::runtime_error: File not valid: file size doesn't match expectation (/Users/kasim/opt/anaconda3/pkgs/cvxpy-1.2.1-py39h2804cbe_0.tar.bz2)
[1]    72073 abort      mamba install cvxpy -c conda-forge
```
