### ISSUE TITLE
Micromamba fails to run Python when installing Pip packages on Windows

### ISSUE THREAD

**Issue by mdekstrand** [mamba-org/mamba#1829]
When instantiating an environment from a file including a `pip` section on Windows, `micromamba` attempts to run `pip` using `python` from the `Scripts` directory instead of the environment root, and fails.

**Example `environment.yml`:**

```yaml
# bootstrap Conda environment file that installs this + deps
name: lkboot
channels:
- conda-forge
- nodefaults
dependencies:
- python>=3.8
- flit=3
- requests=2
- invoke=1
- pip
- conda-lock=1
- mamba
- pip:
  - git+https://github.com/lenskit/lkbuild.git
```

**Command:** (run on Window)

    micromamba create -n lkboot -f environment.yml

**Expected behavior:** micromamba creates the environment

**Observed behavior:**

```
Installing pip packages: git+https://github.com/lenskit/lkbuild.git
'C:\Users\michaelekstrand\Documents\LensKit\mm\mmbase\envs\lkboot\Scripts\python' is not recognized as an internal or external command,
operable program or batch file.
critical libmamba pip failed to install packages
```
