### ISSUE TITLE
How to make pip packages available in micromamba environment

### ISSUE THREAD

**Issue by lgonzalezsa** [mamba-org/mamba#1899]
With conda was able to create environment having majority of the packages from conda and conda-forge but when needed like in the case of rpy2 (3.5) and paramiko (2.11) need to use pip install for those and then able to use them in the environment.
How can I do the same with micromamba? it is possible?
I did install rpy2 and paramiko but in the activated micromamba environment not able to import them.
Am using docker to build image with the dev environment.

**Comment by lgonzalezsa** [comment]
Update: when I was installing pip packages I assume the `micromamba activate environment` will let the python binary to be the one calling it in docker as relative path, but changing it to absolute path then able to import the pip installed packages.

When I ran conda activate I had no issue, is this expected to be in micromamba or might be because am using it inside of docker?

Idea from here: https://stackoverflow.com/questions/69870515/with-mamba-pypy-cannot-find-modules-installed-using-pip

**Comment by wholtz** [comment]
Hello @lgonzalezsa. Are `ipython` and `pip` installed within your `gtcs-dataanalysis` conda environment or are they coming from somewhere else (what is the output of `which ipython` and `which pip`)?

Are you aware that you can define a conda environment like this:

```yaml
name: base
channels:
  - conda-forge
dependencies:
  - ipython=8.4.0
  # I don't know if you need numpy, but showing how to install python packages from a conda repo:
  - numpy=1.23.0
  - pip:
     - rpy2==3.5.4
     - paramiko==2.11.0
```

If your goal is to build a docker image, you might want to check out [mamba-org/micromamba-docker](https://github.com/mamba-org/micromamba-docker). Or we even have an image specialized for dev environments [mamba-org/micromamba-devcontainer](https://github.com/mamba-org/micromamba-devcontainer).
