### ISSUE TITLE
[Micromamba] enable CLI to specify bashrc path

### ISSUE THREAD

**Issue by bretttully** [mamba-org/mamba#1904]
On Circle CI, I had to reverse engineer the micromaba install steps because they use a custom path for `$BASH_ENV` and I couldn't get the default results of init in `~/.bashrc` to work.

Given the specified use case of micromamba in CI, this felt a little awkward. Maybe (probably?) I'm doing something wrong, but I couldn't tell from the docs.

```yaml
  micromamba_install: &micromamba_install
    run:
      name: Install micromamba
      no_output_timeout: 20m
      command: |
        echo "********************** download and install micromamba"
        mkdir -p ~/.local/bin
        curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj -C ~/.local/bin/ --strip-components=1 bin/micromamba

        echo "********************** init micromamba shell"
        echo 'export MAMBA_EXE="~/.local/bin/micromamba"' >> $BASH_ENV
        echo 'export MAMBA_ROOT_PREFIX="~/micromamba"' >> $BASH_ENV
        echo '__mamba_setup="$(~/.local/bin/micromamba shell hook --shell bash --prefix ~/micromamba 2> /dev/null)"' >> $BASH_ENV
        echo 'eval "$__mamba_setup"' >> $BASH_ENV

  conda_setup: &conda_setup
    run:
      name: Install dependencies
      no_output_timeout: 20m
      command: |
        echo "********************** initialise micromamba"
        source $BASH_ENV

        echo "********************** Create the environment"
        micromamba create -y -f environment.yaml
```

**Comment by wolfv** [comment]
Thanks for the note. Do you know if `$BASH_ENV` is a custom variable or widely supported?

**Comment by jonashaag** [comment]
Do I understand correctly that they have `.bashrc` somewhere else and have an environment variable `BASH_ENV=/path/to/.bashrc`?

**Comment by bretttully** [comment]
For whatever reason (that I don't understand) circleci wouldn't allow me to `source ~/.bashrc`, so running the recommended install script would not set up micromamba correctly and it was not possible to create the environment.

**Comment by wholtz** [comment]
> Thanks for the note. Do you know if `$BASH_ENV` is a custom variable or widely supported?

`$BASH_ENV` is part of the `bash` startup process, as described in [this section of the bash docs](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html#Invoked-non_002dinteractively).

But it is unclear to me exactly how CircleCI is attempting to make use of `BASH_ENV`....

**Comment by wholtz** [comment]
After reading the CircleCI docs a bit more this is starting to make some sense. The key line of the docs (which is in the little screen shot above), is "share environmental variables across `run` steps".  I'm not sure if `micromamba_install:` and `conda_setup:` are defining `jobs` or `steps`. But if they are defining `jobs` then I don't think `$BASH_ENV` will retain its value from `micromamba_install:` to `conda_setup:`

**Comment by bretttully** [comment]
>I'm not sure if micromamba_install: and conda_setup: are defining jobs or steps.

Here I am using them to define steps with a job -- so in this case, if `micromamba` could send its init to `$BASH_ENV` I'm reasonably sure everything would work.

**Comment by rshkv** [comment]
This ended up _mostly_ working for me:

```yaml
commands:
  setup-env:
    steps:
       # ...
       - run:
          name: Install environment
          command: /home/circleci/bin/micromamba install --name base --file ./dev/ci-environment.yml
      - run:
          name: Initialize Micromamba
          command: echo 'eval "$(/home/circleci/bin/micromamba shell hook --shell=bash)"' >> "$BASH_ENV"
      - run:
          name: Initialize Conda and activate base environment
          command: echo 'micromamba activate base' >> "$BASH_ENV"
```

I couldn't get `boa build` or `conda mambabuild` to work, but I didn't have other problems.
