### ISSUE TITLE
Handle <TOKEN> in conda-lock v2 files

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1923]
```sh
# Create environment.yml:
echo 'channels: [some-authenticated-channel, conda-forge]' > environment.yml
echo 'dependencies: [some-authenticated-package]' >> environment.yml

# Create lock file:
conda-lock --platform osx-arm64

# Tokens are represented as <TOKEN> in conda-lock.yml:
grep TOKEN conda-lock.yml
# Note that if there are multiple distinct tokens (by multiple authenticated channels), ALL of them are represented as <TOKEN>

# This fails:
micromamba create conda-lock.yml -n lock123
```

**Comment by jonashaag** [comment]
cc @ThomasBlauthQC @pavelzw

**Comment by sanzoghenzo** [comment]
I think I'm hitting the same issue here, but I'm not sure it is the exact problem.

To expand on this (and to have confirmation from @jonashaag that it has the same problem), my environment look like this:

```yml
name: test-env
channels:
  - https://my-repo.local/t/$QUETZ_API_KEY/channels/stable
  - conda-forge
dependencies: [...]
```
since I specified an environment variable, my `conda-lock.yml` doesn't use `<TOKEN>`, but correctly reports the envvar:
```yml
metadata:
  channels:
    - url: https://my-repo.local/t/$QUETZ_API_KEY/channels/stable
      used_env_vars:
        - QUETZ_API_KEY
    - url: conda-forge
      used_env_vars: []
  content_hash:
    linux-64: 7990ba69418de229c9b451e474195eb23a06c8e535f5842ec9d8eeff3e051955
  platforms:
    - linux-64
```
if I try to use this lock file, though, I got
```shell
$ micromamba create -p /tmp/env --yes --file conda-lock.yml
...
Transaction starting
critical libmamba Download error (6) Couldn't resolve host name [https://my-repo.local$QUETZ_API_KEY/channels/stable/noarch/pysws-utils-2.5.2-pypy_0.tar.bz2]
    Could not resolve host: my-repo.local$QUETZ_API_KEY
```

It looks a lot like this [conda issue](https://github.com/conda/conda/issues/10018) I've stumbled upon some time ago, in which I suggested to change the token regex to `/t/(.*?)/` and then expand the environment variable.

Of course, the regex could be left as is if the environment variable is expanded before the regex parsing!
