### ISSUE TITLE
Error `critical libmamba filesystem error: cannot get file size: Is a directory` while using 0.26.0

### ISSUE THREAD

**Issue by pnuu** [mamba-org/mamba#1979]
I got this error building my applications with the latest micromamba 0.26.0:

```bash
critical libmamba filesystem error: cannot get file size: Is a directory [/opt/conda/pkgs/pip-22.2.2-pyhd8ed1ab_0/site-packages]
```

To reproduce:

```bash
micromamba install -y -f /tmp/env.yaml
micromamba remove -y --force pip
micromamba clean -a -y
```

with the following `env.yaml`

```yaml
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pyyaml
```

The installation of `pyyaml` isn't necessary, but illustrates the usage I am doing (minimizing the size of my app container).

I have a feeling this is related to #1975
