### ISSUE TITLE
~/.mambarc ignored by Mamba, but not Micromamba

### ISSUE THREAD

**Issue by yarnabrina** [mamba-org/mamba#1999]
I installed the latest version of `Mambaforge` and set up a configuration file identical to my stable `.condarc` file. While creating a new environment or anything else for that matter, this file is not respected at all, even though this should have been according to [this](https://mamba.readthedocs.io/en/latest/user_guide/configuration.html).

## Reproducible setup

Used configuration file

```yaml
channels: ### the list of conda channels to include for relevant operations
  - defaults
  - conda-forge

channel_priority: strict ### with strict channel priority, packages in lower priority channels are not considered if a package with the same name appears in a higher priority channel

create_default_packages: ### packages that are by default added to a newly created environments
  - python>=3.7

always_yes: false ### automatically choose the 'yes' option whenever asked to proceed with a conda operation

auto_activate_base: false ### automatically activate the base environment during shell initialization

add_pip_as_python_dependency: true ## add pip, wheel, and setuptools as dependencies of Python
```

Used command

```bash
mamba create --name test
```

This should try to create a new environment with python version >= 3.7. And that did not happen, and an environment got created with no package and without python itself.

## Workaround

Just renaming the file from `~/.mambarc` to `~/.condarc` solves the issue.

**Comment by yarnabrina** [comment]
I was trying `micromamba` in a test docker container in WSL, and `envs_dirs` do not seem to work, and renaming file does not solve the issue.

## Reproducible Example:

### Steps

1. New docker container of latest Ubuntu LTS

```bash
docker run --rm -it ubuntu:22.04
```

2. Install dependencies

```bash
apt-get update && apt-get install -y --no-install-recommends bzip2 ca-certificates curl vim
```

3. Install `micromamba`

```bash
curl micro.mamba.pm/install.sh | bash
```

4. Load bash with mamba initialised

```bash
source ~/.bashrc
```

5. Create mamba configurations file at `~/.mambarc`

```yaml
envs_dirs:
  - ${HOME}/my-mamba-env-dir
show_banner: false
```

6. Create a new environment

```bash
micromamba create -n test
```

### What happens

It creates the `test` environment at `/root/micromamba/envs/test`.

### What is expected

It should create the `test` environment at `/root/my-mamba-env-dir/test`

## Extra Information

As far as I can see, the configuration is detected correctly:

```bash
root@8a4e815863ed:/# micromamba config list
envs_dirs:
  - /root/my-mamba-env-dir
show_banner: false
root@8a4e815863ed:/# micromamba config describe
# envs_dirs
#   Possible locations of named environments

# show_banner
#   Show the banner
```

Renaming the file to `~/.condarc` has no effect.

Micromamba version

```bash
root@8a4e815863ed:/# micromamba info

            environment : None (not found)
           env location : -
      user config files : /root/.mambarc
 populated config files : /root/.mambarc
       libmamba version : 0.27.0
     micromamba version : 0.27.0
           curl version : libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.5
       virtual packages : __unix=0=0
                          __linux=5.15.68=0
                          __glibc=2.35=0
                          __archspec=1=x86_64
               channels :
       base environment : /root/micromamba
               platform : linux-64
```

Given this, it seems to be a hug instead of a documentation issue. @jonashaag, let me know if any more information will help you in finding the cause of this.
