### ISSUE TITLE
`--dry-run` crashing with `- pip:`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2073]
```yml
dependencies:
  - pip
  - pip:
    - pip  # Or anything else
```

```
$ micromamba create -f t.yml -y --dry-run -n x
...
critical libmamba Cannot activate, prefix does not exist at: /Users/j/micromamba/envs/x
/var/folders/8v/x6lkdp6110d5w7z73g_jfm_00000gn/T/mambafwPMhAauGPH: line 5: : command not found
critical libmamba pip failed to install packages
```
