### ISSUE TITLE
micromamba coredump

### ISSUE THREAD

**Issue by urucoder** [mamba-org/mamba#2095]
Hi! I'm trying to build an environment using micromamba, but it fails with a core dump in a machine with 32 GB of ram.

I'm running it as

> micromamba create -n test-env -f environment.yml -y

and receiving the error

> micromamba: /home/conda/feedstock_root/build_artifacts/libsolv_1649959712616/work/src/rules.c:261: solver_addrule: Assertion `!p2 && d > 0' failed.
Aborted (core dumped)

I'm adding the YAML as a reference here and it would be great to know how to provide more details to fix this.

<details>

<summary>Long environment</summary>

```YAML
name: base
channels:
  - pytorch
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex>=0.1
  - _openmp_mutex>=4.5
  - _pytorch_select>=0.2
  - abseil-cpp
  - aiohttp
  - aiosignal
  - arrow-cpp
  - async-timeout
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-common
  - azure-core
  - azure-identity
  - azure-keyvault
  - azure-kusto-data
  - azure-servicebus
  - azure-storage-blob
  - azure-storage-common
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas
  - blinker
  - bpemb
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - conda
  - conda-content-trust
  - conda-package-handling
  - conllu
  - contourpy
  - cryptography>=38.0.3
  - cudatoolkit>=11.0.3
  - cvxpy
  - cycler
  - dataclasses
  - datasets
  - deprecated
  - dill
  - ecos
  - faiss
  - faiss-gpu
  - ffmpeg
  - filelock
  - fmt
  - fonttools
  - freetype
  - frozenlist
  - fsspec
  - ftfy
  - funcy
  - future
  - gdown
  - gensim
  - gflags
  - giflib
  - glog
  - gmp
  - gnutls
  - grpc-cpp
  - huggingface_hub
  - hyperopt
  - icu
  - idna
  - ijson
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - isodate
  - janome
  - javaobj-py3>=0.4.3
  - jinja2
  - joblib>=1.2.0
  - jpeg>=9e
  - jsonschema
  - keyutils
  - kiwisolver
  - konoha
  - krb5
  - lame
  - langdetect
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libarchive
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libfaiss
  - libfaiss-avx2
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - libiconv
  - liblapack
  - libmamba
  - libmambapy
  - libnghttp2
  - libnsl
  - libpng
  - libprotobuf
  - libsolv
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libthrift
  - libtiff
  - libutf8proc
  - libuuid
  - libuv
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - llvm-openmp
  - lxml>=4.9.1
  - lz4
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib-base
  - mkl
  - more-itertools
  - mpld3
  - msal
  - msal-extensions
  - msrest
  - multidict
  - multiprocess
  - munkres
  - ncurses
  - nettle
  - networkx
  - nltk>=3.6.7
  - numexpr
  - numpy>=1.23.4
  - oauthlib
  - onnx
  - onnxruntime
  - openh264
  - openjpeg
  - openssl
  - orc
  - orderedset
  - osqp
  - overrides
  - packaging
  - pandarallel
  - pandas
  - parquet-cpp
  - path
  - pcre
  - pcre2
  - pillow>=9.2.0
  - pip
  - pkgutil-resolve-name
  - platformdirs>=2.5.2
  - portalocker
  - pptree
  - protobuf>3.19.4
  - psutil
  - pthread-stubs
  - py4j
  - pyarrow
  - pybind11-abi
  - pyclustering
  - pycosat
  - pycparser
  - pyemd
  - pyjwt
  - pyldavis
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python>=3.9
  - python-dateutil>=2.8.2
  - python-flair>=0.8
  - python-flatbuffers
  - python-xxhash
  - python_abi
  - pytorch
  - pytorch-mutex==1.0=cuda
  - pytz
  - pyyaml
  - qdldl-python
  - re2
  - readline
  - regex
  - reproc
  - reproc-cpp
  - requests
  - requests-oauthlib
  - responses
  - ruamel_yaml
  - s2n
  - sacremoses
  - scikit-learn
  - scipy
  - scs
  - segtok
  - sentence-transformers
  - sentencepiece
  - setuptools
  - six
  - smart_open
  - snappy
  - soupsieve
  - sqlite
  - sqlitedict
  - tabulate
  - tbb
  - threadpoolctl
  - tk
  - tokenizers
  - toolz
  - torchtext
  - tqdm
  - transformers
  - typing-extensions
  - typing_extensions
  - tzdata
  - uamqp
  - unicodedata2
  - uritools
  - urllib3
  - wcwidth
  - wheel
  - wikipedia-api
  - wrapt
  - xlsxwriter
  - xorg-kbproto
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-xextproto
  - xorg-xproto
  - xxhash
  - xz
  - yaml
  - yaml-cpp
  - yarl
  - zipp
  - zlib
  - zstd
  - pip:
    - aia
    - autograd-minimize
    - compress-fasttext
    - langid
    - lexrank
    - onnxruntime-extensions
    - path-py
    - pylocus
    - urlextract
    - wmd
prefix: /opt/conda
```

</details>
