### ISSUE TITLE
`Channel::name()` is wrong for token-based channel URLs

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2179]
We have channels like this

```yml
channels:
  - xxx
  - conda-forge
custom_channels:
  xxx: https://some.quetz.url/t/tokentokentokentoken/get
```

For the `xxx` channel the `Channel::name()` is `xxx/get` instead of `xxx`. This doesn't surface so far but I guess it will break name-based matching if we have that anywhere.

One way to reproduce this is to add the following line here: https://github.com/mamba-org/mamba/blob/68ed35ba131dbe3cd0d355d2a8f5ecd97511d861/libmamba/src/api/info.cpp#L161-L164

```c++
                channel_urls.push_back(channel->name());
```

fyi @janjaguschqc maybe this will surface for our internal Quetz based channels at some point
