### ISSUE TITLE
Verification error of the certificatewhen using custom mirror source

### ISSUE THREAD

**Issue by Axolotl233** [mamba-org/mamba#2286]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

searched, mostly about mamba, not micromamba 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Reproducible with Conda

### Describe your issue

Hi community,

Because of network problem, I set conda mirror sites described #1902, but i get a new error when install the package:

`SSL peer certificate or SSH remote key was not OK`

I have tested that miniconda is normally working when using these mirror sites, so how to fix it with micromamba?

Thanks,
Nemo

### mamba info / micromamba info

```shell
`
            environment : test (active)
           env location : /home/mouwenjie/software/micromamba/envs/test
      user config files : /home/mouwenjie/.mambarc
 populated config files : /home/mouwenjie/.condarc
       libmamba version : 1.3.1
     micromamba version : 1.3.1
           curl version : libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=3.10.0=0
                          __glibc=2.17=0
                          __archspec=1=x86_64
               channels : https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
       base environment : /home/user101/software/micromamba
               platform : linux-64
`
```

### Logs

```shell
`
critical libmamba Multiple errors occured:
    Download error (60) SSL peer certificate or SSH remote key was not OK [https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch/repodata.json]
    SSL certificate problem: certificate has expired
    Subdir anaconda/pkgs/main/noarch not loaded!
    Subdir anaconda/pkgs/free/noarch not loaded!
    Subdir anaconda/pkgs/r/noarch not loaded!
`
```

### ~/.condarc

```yaml
`
channels:
  - defaults
default_channels:
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r
custom_channels:
  conda-forge: https://mirrors.bfsu.edu.cn/anaconda/cloud
  biobakery: https://mirrors.bfsu.edu.cn/anaconda/cloud
  bioconda: https://mirrors.bfsu.edu.cn/anaconda/cloud
show_channel_urls: true
`
```
