### ISSUE TITLE
Resolving a few packages takes +8h

### ISSUE THREAD

**Issue by jmakov** [mamba-org/mamba#2379]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

slow

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Didn't try

### Describe your issue

Trying to install this packages takes almost half a day (still running):
```shell
Looking for: ['datashader', 'holoviews', 'hvplot', 'ipywidgets', 'jupyter-resource-usage', 'jupyterlab', 'jupyter_contrib_nbextensions', 'jupyterlab_execute_time', 'jupyterlab_widgets', 'jupyterlab-variableinspector', 'nodejs', 'numpy', 'pandas', 'polars', 'scipy', 'scikit-learn-intelex']
```

### mamba info / micromamba info

```shell
active environment : rapids
    active env location : /opt/conda/envs/rapids
            shell level : 1
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/rapidsai/linux-64
                          https://conda.anaconda.org/rapidsai/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
                          https://conda.anaconda.org/gpuci/linux-64
                          https://conda.anaconda.org/gpuci/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Linux/5.15.0-67-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### environment.yml

```yaml
channels:
  - intel
  - conda-forge
  - defaults

dependencies:
  - datashader
  - holoviews
  - hvplot
  - ipywidgets
  - jupyter-resource-usage
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyterlab_execute_time
  - jupyterlab_widgets
  - jupyterlab-variableinspector
  - nodejs
  - numpy
  - pandas
  - polars
  - scipy
  - scikit-learn-intelex
```
