### ISSUE TITLE
--json flag does not return the entire list of solver problem in solver_problems

### ISSUE THREAD

**Issue by dan-blanchard** [mamba-org/mamba#2513]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

json solver_problems

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

When trying to create an environment with micromamba, if I use the `--json` flag to create, it does not yield the full list of solver issues inside the `solver_problems` value. Instead, it just seems to return a random problem (that isn't even exactly the same as the ones listed in the full view).

With `--json`:

```
$ micromamba create -r /opt/coiled/rt -p /opt/coiled/env -y --no-pyc --json -f /tmp/tmpya0nlqzi.yml
{
    "solver_problems": [
        "package libarrow-12.0.0-h07599e3_0_cuda requires libevent >=2.1.12,<2.1.13.0a0, but none of the providers can be installed"
    ],
    "success": false
}
```

Without `--json`:

```
$ micromamba create -r /opt/coiled/rt -p /opt/coiled/env -y --no-pyc -f /tmp/tmpya0nlqzi.yml

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ libarrow ~=12.0.0  is installable and it requires
    │  └─ libevent >=2.1.12,<2.1.13.0a0 , which can be installed;
    ├─ matplotlib ~=3.7.1  is installable with the potential options
    │  ├─ matplotlib 3.7.1 would require
    │  │  └─ pyqt >=5.10  with the potential options
    │  │     ├─ pyqt [5.12.3|5.15.4|5.15.7] would require
    │  │     │  ├─ pyqtwebengine 5.12.1 py37he336c9b_5, which requires
    │  │     │  │  └─ python_abi 3.7.* *_cp37m, which can be installed;
    │  │     │  └─ python_abi 3.7.* *_cp37m, which can be installed;
    │  │     ├─ pyqt 5.12.3 would require
    │  │     │  └─ python >=2.7,<2.8.0a0 , which can be installed;
    │  │     ├─ pyqt 5.12.3 would require
    │  │     │  └─ pyqtwebengine 5.12.1 py310hfcd6d55_8, which requires
    │  │     │     └─ qt >=5.12.9,<5.13.0a0  with the potential options
    │  │     │        ├─ qt 5.12.9 would require
    │  │     │        │  └─ jpeg >=9e,<10a , which can be installed;
    │  │     │        └─ qt 5.12.9 would require
    │  │     │           └─ jpeg >=9d,<10a , which can be installed;
    │  │     ├─ pyqt 5.12.3 would require
    │  │     │  └─ python_abi 3.6.* *_cp36m, which can be installed;
    │  │     ├─ pyqt 5.12.3 would require
    │  │     │  └─ python >=3.6,<3.7.0a0 , which can be installed;
    │  │     ├─ pyqt 5.12.3 would require
    │  │     │  └─ python >=3.7,<3.8.0a0 , which can be installed;
    │  │     ├─ pyqt [5.12.3|5.15.4|5.15.7] would require
    │  │     │  └─ python_abi 3.8.* *_cp38, which can be installed;
    │  │     ├─ pyqt 5.12.3 would require
    │  │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
    │  │     ├─ pyqt [5.12.3|5.15.4|5.15.7] would require
    │  │     │  └─ python_abi 3.9.* *_cp39, which can be installed;
    │  │     ├─ pyqt [5.15.4|5.15.7] would require
    │  │     │  └─ qt-main [>=5.15.3,<5.16.0a0 |>=5.15.4,<5.16.0a0 |>=5.15.6,<5.16.0a0 ] with the potential options
    │  │     │     ├─ qt-main [5.15.2|5.15.3|5.15.4|5.15.6|5.15.8] would require
    │  │     │     │  └─ jpeg >=9e,<10a , which can be installed;
    │  │     │     └─ qt-main 5.15.8 would require
    │  │     │        └─ libevent >=2.1.10,<2.1.11.0a0 , which conflicts with any installable versions previously reported;
    │  │     ├─ pyqt 5.15.4 would require
    │  │     │  └─ qt-main >=5.15.2,<5.16.0a0  with the potential options
    │  │     │     ├─ qt-main [5.15.2|5.15.3|5.15.4|5.15.6|5.15.8], which can be installed (as previously explained);
    │  │     │     ├─ qt-main 5.15.8, which cannot be installed (as previously explained);
    │  │     │     └─ qt-main 5.15.2 would require
    │  │     │        └─ jpeg >=9d,<10a , which can be installed;
    │  │     └─ pyqt 5.15.7 would require
    │  │        └─ python_abi 3.11.* *_cp311, which can be installed;
    │  ├─ matplotlib 3.7.1 would require
    │  │  └─ python_abi 3.11.* *_cp311, which can be installed;
    │  ├─ matplotlib 3.7.1 would require
    │  │  └─ pypy3.8 >=7.3.11 , which can be installed;
    │  ├─ matplotlib 3.7.1 would require
    │  │  └─ python_abi 3.8.* *_cp38, which can be installed;
    │  ├─ matplotlib 3.7.1 would require
    │  │  └─ pypy3.9 >=7.3.11 , which can be installed;
    │  └─ matplotlib 3.7.1 would require
    │     └─ python_abi 3.9.* *_cp39, which can be installed;
    ├─ pillow ~=9.5.0  is installable with the potential options
    │  ├─ pillow 9.5.0 would require
    │  │  └─ libjpeg-turbo >=2.1.5.1,<3.0a0 , which requires
    │  │     └─ jpeg <0.0.0a , which conflicts with any installable versions previously reported;
    │  ├─ pillow 9.5.0 would require
    │  │  └─ python_abi 3.11.* *_cp311, which can be installed;
    │  ├─ pillow 9.5.0 would require
    │  │  └─ python_abi 3.8.* *_cp38, which can be installed;
    │  ├─ pillow 9.5.0 would require
    │  │  └─ pypy3.8 >=7.3.11 , which can be installed;
    │  ├─ pillow 9.5.0 would require
    │  │  └─ python_abi 3.9.* *_cp39, which can be installed;
    │  └─ pillow 9.5.0 would require
    │     └─ pypy3.9 >=7.3.11 , which can be installed;
    └─ python 3.10.10  is uninstallable because it requires
       └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

### mamba info / micromamba info

```shell
environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files :
       libmamba version : 1.4.2
     micromamba version : 1.4.2
           curl version : libcurl/7.88.1 OpenSSL/3.1.0 zlib/1.2.13 zstd/1.5.2 libssh2/1.10.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=5.15.49=0
                          __glibc=2.31=0
                          __archspec=1=x86_64
               channels :
       base environment : /opt/conda
               platform : linux-64
```

### Logs

```shell
{
    "solver_problems": [
        "package libarrow-12.0.0-h07599e3_0_cuda requires libevent >=2.1.12,<2.1.13.0a0, but none of the providers can be installed"
    ],
    "success": false
}
```

### environment.yml

```yaml
name: coiled
channels:
- conda-forge
channel-priority: strict
dependencies:
- zstd
- zlib
- zipp~=3.15.0
- zict~=3.0.0
- zeromq
- ypy-websocket~=0.8.2
- yarl~=1.9.1
- yaml~=0.2.5
- y-py~=0.5.9
- xz
- xyzservices~=2023.2.0
- xorg-libxdmcp~=1.1.3
- xorg-libxau~=1.0.9
- widgetsnbextension~=4.0.7
- wheel~=0.40.0
- websocket-client~=1.5.1
- webencodings~=0.5.1
- wcwidth~=0.2.6
- urllib3~=1.26.15
- unicodedata2~=15.0.0
- python-tzdata==2023.3
- tzdata==2023c
- typing_extensions~=4.5.0
- traitlets~=5.9.0
- tornado==6.3
- toolz~=0.12.0
- tomli~=2.0.1
- tk
- tinycss2~=1.2.1
- terminado~=0.17.1
- tblib~=1.7.0
- stack_data~=0.6.2
- soupsieve~=2.3.2.post1
- sortedcontainers~=2.4.0
- sniffio~=1.3.0
- snappy
- six~=1.16.0
- setuptools~=67.7.2
- s3transfer~=0.6.0
- rich~=13.3.5
- rfc3986-validator~=0.1.1
- rfc3339-validator~=0.1.4
- requests~=2.29.0
- readline
- re2
- pyzmq~=25.0.2
- pytz==2023.3
- python_abi==3.10
- python-json-logger~=2.0.7
- python-dateutil~=2.8.2
- python==3.10.10
- pyrsistent~=0.19.3
- pyparsing~=3.0.9
- pycparser==2.21
- pyarrow~=12.0.0
- pyopenssl~=23.1.1
- pure_eval~=0.2.2
- ptyprocess~=0.7.0
- pthread-stubs==0.4
- psutil~=5.9.5
- prompt-toolkit~=3.0.38
- prometheus_client~=0.16.0
- platformdirs~=3.5.0
- pkgutil-resolve-name~=1.3.10
- pip==23.1.2
- pickleshare~=0.7.5
- pexpect~=4.8.0
- partd~=1.4.0
- parso~=0.8.3
- parquet-cpp~=1.5.1
- pandocfilters~=1.5.0
- pandoc~=2.19.2
- pandas~=2.0.1
- packaging==23.1
- orc
- openjpeg
- numpy~=1.24.3
- notebook-shim~=0.2.3
- notebook~=6.5.4
- nest-asyncio~=1.5.6
- ncurses
- nbformat~=5.8.0
- nbconvert-pandoc~=7.3.1
- nbconvert~=7.3.1
- nbconvert-core~=7.3.1
- nbclient~=0.7.4
- nbclassic~=0.5.6
- munkres~=1.1.4
- multidict~=6.0.4
- msgpack-python==1.0.5
- mistune~=2.0.5
- mdurl~=0.1.0
- matplotlib-inline~=0.1.6
- matplotlib~=3.7.1
- matplotlib-base~=3.7.1
- markdown-it-py~=2.2.0
- lz4-c
- lz4~=4.3.2
- locket~=1.0.0
- llvm-openmp
- libzlib~=1.2.13
- libxcb==1.13
- libwebp-base
- libutf8proc~=2.8.0
- libtiff
- libthrift
- libssh2
- libsqlite
- libsodium~=1.0.18
- libprotobuf
- libpng
- libopenblas~=0.3.21
- libnghttp2~=1.52.0
- liblapack
- libjpeg-turbo
- libgrpc
- libgoogle-cloud
- libgfortran5
- libgfortran
- libffi
- libevent
- libev
- libedit~=3.1.20191231
- libdeflate
- libcxx~=16.0.2
- libcurl
- libcrc32c
- libcblas
- libbrotlienc~=1.0.9
- libbrotlidec~=1.0.9
- libbrotlicommon~=1.0.9
- libblas
- libarrow~=12.0.0
- lerc
- lcms2==2.15
- krb5
- kiwisolver~=1.4.4
- jupyterlab_server~=2.22.1
- jupyterlab_widgets~=3.0.7
- jupyterlab_pygments~=0.2.2
- jupyterlab~=3.6.3
- jupyter_server_ydoc~=0.8.0
- jupyter_server_terminals~=0.4.4
- jupyter_server_fileid~=0.9.0
- jupyter_server~=2.5.0
- jupyter_core~=5.3.0
- jupyter_client~=8.2.0
- jupyter_ydoc~=0.2.3
- jupyter_events~=0.6.3
- jsonschema~=4.17.3
- jsondiff~=2.0.0
- json5~=0.9.5
- jmespath~=1.0.1
- jedi~=0.18.2
- ipywidgets~=8.0.6
- ipython_genutils~=0.2.0
- ipython~=8.13.1
- ipykernel~=6.22.0
- importlib_resources~=5.12.0
- importlib-metadata~=6.6.0
- idna==3.4
- glog
- gflags
- fsspec~=2023.4.0
- frozenlist~=1.3.3
- freetype
- fonttools~=4.39.3
- flit-core~=3.8.0
- filelock~=3.12.0
- python-fastjsonschema~=2.16.3
- executing~=1.2.0
- entrypoints==0.4
- distributed==2023.4.1
- defusedxml~=0.7.1
- decorator~=5.1.1
- debugpy~=1.6.7
- dask==2023.4.1
- dask-core==2023.4.1
- cytoolz~=0.12.0
- cycler~=0.11.0
- cryptography~=40.0.2
- contourpy~=1.0.7
- comm~=0.1.3
- coiled~=0.6.0
- cloudpickle==2.2.1
- click~=8.1.3
- charset-normalizer~=2.1.1
- cffi~=1.15.1
- certifi~=2022.12.7
- ca-certificates~=2022.12.7
- c-ares
- bzip2
- brotlipy~=0.7.0
- brotli-bin~=1.0.9
- brotli~=1.0.9
- botocore~=1.29.125
- boto3~=1.26.125
- bokeh~=3.1.0
- bleach~=6.0.0
- beautifulsoup4~=4.12.2
- backports.functools_lru_cache~=1.6.4
- backports==1.0
- backoff~=2.2.1
- backcall~=0.2.0
- aws-sdk-cpp
- aws-crt-cpp
- aws-checksums
- aws-c-sdkutils
- aws-c-s3
- aws-c-mqtt
- aws-c-io
- aws-c-http
- aws-c-event-stream
- aws-c-compression~=0.2.16
- aws-c-common
- aws-c-cal
- aws-c-auth
- attrs~=23.1.0
- async-timeout~=4.0.2
- asttokens~=2.2.1
- arrow-cpp
- argon2-cffi-bindings~=21.2.0
- argon2-cffi~=21.3.0
- appnope~=0.1.3
- anyio~=3.6.2
- aiosqlite~=0.19.0
- aiosignal~=1.3.1
- aiohttp~=3.8.4
- aiofiles~=22.1.0
- send2trash~=1.8.2
- pygments~=2.15.1
- pyyaml==6.0
- pysocks~=1.7.1
- pillow~=9.5.0
- markupsafe~=2.1.2
- jinja2~=3.1.2
- babel~=2.12.1
```
