### ISSUE TITLE
Issue with micromamba installer on macOS M1 runners

### ISSUE THREAD

**Issue by beenje** [mamba-org/mamba#2562]
Gitlab.com started to make macOS M1 runners available: https://docs.gitlab.com/ee/ci/runners/saas/macos_saas_runner.html

I'm trying to setup micromamba in CI using the default installer. Default shell is `zsh`.

Using:

```yaml
setup-micromamba-installer-zsh:
  stage: test
  tags:
    - saas-macos-medium-m1
   image: macos-12-xcode-13
   script:
    - echo $SHELL
    - curl micro.mamba.pm/install.sh | zsh
    - eval "$(~/.local/bin/micromamba shell hook -s zsh)"
    - micromamba info
```

Fails with:

```
$ eval "$(~/.local/bin/micromamba shell hook -s zsh)"
$ micromamba info
bash: line 137: : command not found
```

I don't understand where this error is coming from.
If I do the install manually, it works. It sounds like the `shell init` command run by the installer is the one creating the issue.

```yaml
setup-micromamba-manually:
  stage: test
  tags:
    - saas-macos-medium-m1
   image: macos-12-xcode-13
   script:
     - mkdir -p ~/.local/bin ~/micromamba
     - curl -Ls https://micro.mamba.pm/api/micromamba/osx-arm64/latest | tar -xvj -C ~/.local/bin/ --strip-components=1 bin/micromamba
     - eval "$(~/.local/bin/micromamba shell hook -s zsh)"
     - micromamba info
```

```
$ eval "$(~/.local/bin/micromamba shell hook -s zsh)"
$ micromamba info
                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/
            environment : None (not found)
           env location : -
      user config files : /Users/gitlab/.mambarc
 populated config files : 
       libmamba version : 1.4.3
     micromamba version : 1.4.3
           curl version : libcurl/7.88.1 SecureTransport (OpenSSL/3.1.0) zlib/1.2.13 zstd/1.5.2 libssh2/1.10.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __osx=12.6=0
                          __archspec=1=arm64
               channels : 
       base environment : /Users/gitlab/micromamba
               platform : osx-arm64
```

Full logs: https://gitlab.com/MaxIV/test-gitlab-runners/-/pipelines/888384774

I have an intel Mac and can't reproduce the issue.
It might be something specific to how the gitlab runners are configured?
