### ISSUE TITLE
Creating environment, while in an environment: `/libmamba.so.2: undefined symbol: archive_write_add_filter_zstd`

### ISSUE THREAD

**Issue by baraaorabi** [mamba-org/mamba#2567]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

archive_write_add_filter_zstd

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I created an environment, `tskm`, from this file:

```yaml
name: tksm
channels:
  - anaconda 
  - conda-forge
  - bioconda
dependencies:
  - snakemake>=7.0.0
  - python-edlib
  - numpy
  - matplotlib
  - joblib
  - tqdm
  - pandas
  - scikit-learn
  - badread=0.2.0
  - sctagger=1.1
  - minimap2
  - gxx=12.2.0
  - fmt=9.1.0
  - cxxopts=3.1.0
```

Then when I am in this environment, I tried to create a second enviroment, `tksm_bench` from this file:

```yaml
name: tksm_bench
channels:
  - anaconda 
  - conda-forge
  - bioconda
dependencies:
  - matplotlib
  - tqdm
  - upsetplot
  - genion=1.2.3
  - longgf=0.1.2
  - minimap2=2.24
  - nanosim=3.1.0
```

But this failed. Note that I can successfully create the second enviroment (`tksm_bench`) if I am in the `base` environment. The reason why I stubmbled on this issue, is because I was running a Snakemake pipeline in the first environment (`tksm`) and then using the second environment in a Snakemake `conda` directive. I would then run Snakemake with `--use-conda` parameter (which defaults to `mamba` for me). Snakemake reports the same error shown in the log. 
No error is generated when I add `--conda-frontend conda` to Snakemake's command.

### mamba info / micromamba info

```shell
(base) [borabi@linuxsrv005 ~]$ mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : base
    active env location : /home/borabi/mambaforge
            shell level : 1
       user config file : /home/borabi/.condarc
 populated config files : /home/borabi/mambaforge/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /home/borabi/mambaforge  (writable)
      conda av data dir : /home/borabi/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/borabi/mambaforge/pkgs
                          /home/borabi/.conda/pkgs
       envs directories : /home/borabi/mambaforge/envs
                          /home/borabi/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1062.18.1.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 5098:5098
             netrc file : None
           offline mode : False
```

### Logs

```shell
(tksm) [borabi@linuxsrv005 tksm]$ mamba env create -f Benchmark_env.yaml
Traceback (most recent call last):
  File "/home/borabi/mambaforge/envs/tksm/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/borabi/mambaforge/envs/tksm/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/borabi/mambaforge/envs/tksm/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/borabi/mambaforge/envs/tksm/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /home/borabi/mambaforge/envs/tksm/lib/python3.10/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: archive_write_add_filter_zstd
```

### environment.yml

```yaml
name: tksm_bench
channels:
  - anaconda 
  - conda-forge
  - bioconda
dependencies:
  - matplotlib
  - tqdm
  - upsetplot
  - genion=1.2.3
  - longgf=0.1.2
  - minimap2=2.24
  - nanosim=3.1.0
```

### ~/.condarc

```yaml
(base) [borabi@linuxsrv005 ~]$ cat ~/.condarc
cat: /home/borabi/.condarc: No such file or directory
```
