### ISSUE TITLE
Need  faster dependency resolution in "Mamba env"

### ISSUE THREAD

**Issue by 0warning0error** [mamba-org/mamba#2582]
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

mamba env create

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

Creating the environment with `mamba env create -n xxx -f env.yml` will fallback to conda, which will lead to slow dependency resolution. (Completely equivalent to `conda env create -n xxx -f env.yml`). Hope that faster dependency resolution in `mamba env` .

### mamba info / micromamba info

```shell
active environment : base
    active env location : D:\ProgramData\mambaforge
            shell level : 1
       user config file : C:\Users\zyh\.condarc
 populated config files : D:\ProgramData\mambaforge\.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : D:\ProgramData\mambaforge  (writable)
      conda av data dir : D:\ProgramData\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
          package cache : D:\ProgramData\mambaforge\pkgs
                          C:\Users\zyh\.conda\pkgs
                          C:\Users\zyh\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\mambaforge\envs
                          C:\Users\zyh\.conda\envs
                          C:\Users\zyh\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Windows/10 Windows/10.0.22621
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by jonashaag** [comment]
Do you mean `conda create`?

**Comment by 0warning0error** [comment]
> Do you mean `conda create`?

`conda create` is similiar with `conda env create`. But `mamba create` or `conda create` cannot create environment from the yaml file. For example, I have a yaml file **env.yml** like:
```yaml
channels:
  - pytorch
  - conda-forge
dependencies:
  - umap-learn
  - visdom
  - librosa
  - matplotlib>=3.3.0
  - numpy
  - scipy>=1.0.0
  - tqdm
  - python-sounddevice
  - pysoundfile
  - unidecode
  - inflect
  - pyqt5-sip
  - multiprocess
  - numba
  - pypinyin
  - flask
  - flask-wtf
  - flask_cors
  - gevent
  - flask-restx
  - tensorboard
  - streamlit
  - pyyaml
  - torch-complex
  - espnet
  - pywavelets
  - fastapi
  - loguru
  - typer[all]
  - click
  - webrtcvad
  - ffmpeg
  - transformers
```
**`mamba create` or `conda create` cannot create environment from the yaml file.** 

`mamba create -n xxx -f env.yml` or  `conda create -n xxx -f env.yml` will raise an error `CondaValueError: Error reading file, file should be a text file containing packages
conda create --help for details`.

While `mamba env create` or `conda env create`  can do it. `mamba env create -n xxx -f env.yml` will create a virtual environment where dependencies listed in the yaml file are installed. But I found that `mamba env create -n xxx -f env.yml` will fall back to conda. This will lead to slow dependency resolution. Here is the relative code:
```python
#mamba.py

def main(*args, **kwargs):
    # Set to false so we don't allow uploading our issues to conda!
    context.report_errors = False

    from conda.common.compat import ensure_text_type

    if "activate" in sys.argv or "deactivate" in sys.argv:
        print(
            "Run 'mamba init' to be able to run mamba activate/deactivate\n"
            "and start a new shell session. Or use conda to activate/deactivate.\n",
            file=sys.stderr,
        )
        return sys.exit(-1)

    if not args:
        args = sys.argv

    if len(args) == 2 and args[1] == "--version":
        from mamba._version import __version__

        print("mamba {}".format(__version__))

    args = tuple(ensure_text_type(s) for s in args)

    if len(args) > 2 and args[1] == "env" and args[2] in ("create", "update"):
        # special handling for conda env create!
        from mamba import mamba_env

        return mamba_env.main()
``` 

```python
# mamba_env.py
def main():
    from conda_env.cli.main import main as conda_env_main

    sys.argv = sys.argv[0:1] + sys.argv[2:]
    return conda_env_main()
```

Apparently, when I enter `mamba env create -n xxx -f env.yml`, the result is equivalent to that of `conda env create -n xxx -f env.yml`. 

These above are what I mean.
