### ISSUE TITLE
md5 and sha256 sum unknown

### ISSUE THREAD

**Issue by SinisterMJ** [mamba-org/mamba#2674]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

Found nothing similar.

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

In our dockerfile we have following line 

RUN conda install mamba -q -c conda-forge \
  && mamba env update -q -n base -f environment.yml
  
This runs fine with mamba 1.4.7 (checked by pinning version to mamba==1.4.7), but with 1.4.9 it crashes:

```
The following NEW packages will be INSTALLED:
  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5 
  llvm-openmp        conda-forge/linux-64::llvm-openmp-16.0.6-h4dfa4b3_0 
  mamba              conda-forge/linux-64::mamba-1.4.9-py311h3072747_0 
  python_abi         conda-forge/linux-64::python_abi-3.11-2_cp311 
The following packages will be REMOVED:
  libgomp-11.2.0-h1234567_1
The following packages will be UPDATED:
  libcurl               pkgs/main::libcurl-8.1.1-h251f7ec_1 --> conda-forge::libcurl-8.1.2-h409715c_0 
  libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-13.1.0-he5830b7_0 
  libmamba             pkgs/main::libmamba-1.4.1-h2dafd23_1 --> conda-forge::libmamba-1.4.9-h658169a_0 
  libmambapy         pkgs/main::libmambapy-1.4.1-py311h2da~ --> conda-forge::libmambapy-1.4.9-py311h527f279_0 
  libsolv              pkgs/main::libsolv-0.7.22-he621ea3_0 --> conda-forge::libsolv-0.7.24-hfc55251_1 
  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-13.1.0-hfd8a6a1_0 
  openssl               pkgs/main::openssl-3.0.9-h7f8727e_0 --> conda-forge::openssl-3.1.1-hd590300_1 
  zlib                    pkgs/main::zlib-1.2.13-h5eee18b_0 --> conda-forge::zlib-1.2.13-hd590300_5 
The following packages will be SUPERSEDED by a higher-priority channel:
  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_kmp_llvm 
  ca-certificates    pkgs/main::ca-certificates-2023.05.30~ --> conda-forge::ca-certificates-2023.5.7-hbcca054_0 
  certifi            pkgs/main/linux-64::certifi-2023.5.7-~ --> conda-forge/noarch::certifi-2023.5.7-pyhd8ed1ab_0 
Proceed ([y]/n)? 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
warning  libmamba Could not validate package '/opt/miniconda/pkgs/six-1.16.0-pyhd3eb1b0_1/info/repodata_record.json': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Extracted package cache '/opt/miniconda/pkgs/six-1.16.0-pyhd3eb1b0_1 couldn't be validated due to runtime error: Could not set URL (code: 14 - url = /six-1.16.0-pyhd3eb1b0_1.conda)
warning  libmamba Could not validate package '/opt/miniconda/pkgs/six-1.16.0-pyhd3eb1b0_1.conda': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Could not validate package '/opt/miniconda/pkgs/pycparser-2.21-pyhd3eb1b0_0/info/repodata_record.json': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Extracted package cache '/opt/miniconda/pkgs/pycparser-2.21-pyhd3eb1b0_0 couldn't be validated due to runtime error: Could not set URL (code: 14 - url = /pycparser-2.21-pyhd3eb1b0_0.conda)
warning  libmamba Could not validate package '/opt/miniconda/pkgs/pycparser-2.21-pyhd3eb1b0_0.conda': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Could not validate package '/opt/miniconda/pkgs/jsonpointer-2.1-pyhd3eb1b0_0/info/repodata_record.json': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Extracted package cache '/opt/miniconda/pkgs/jsonpointer-2.1-pyhd3eb1b0_0 couldn't be validated due to runtime error: Could not set URL (code: 14 - url = /jsonpointer-2.1-pyhd3eb1b0_0.conda)
warning  libmamba Could not validate package '/opt/miniconda/pkgs/jsonpointer-2.1-pyhd3eb1b0_0.conda': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Could not validate package '/opt/miniconda/pkgs/charset-normalizer-2.0.4-pyhd3eb1b0_0/info/repodata_record.json': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Extracted package cache '/opt/miniconda/pkgs/charset-normalizer-2.0.4-pyhd3eb1b0_0 couldn't be validated due to runtime error: Could not set URL (code: 14 - url = /charset-normalizer-2.0.4-pyhd3eb1b0_0.conda)
warning  libmamba Could not validate package '/opt/miniconda/pkgs/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Could not validate package '/opt/miniconda/pkgs/jsonpatch-1.32-pyhd3eb1b0_0/info/repodata_record.json': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Extracted package cache '/opt/miniconda/pkgs/jsonpatch-1.32-pyhd3eb1b0_0 couldn't be validated due to runtime error: Could not set URL (code: 14 - url = /jsonpatch-1.32-pyhd3eb1b0_0.conda)
warning  libmamba Could not validate package '/opt/miniconda/pkgs/jsonpatch-1.32-pyhd3eb1b0_0.conda': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Could not validate package '/opt/miniconda/pkgs/certifi-2023.5.7-pyhd8ed1ab_0/info/repodata_record.json': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
warning  libmamba Extracted package cache '/opt/miniconda/pkgs/certifi-2023.5.7-pyhd8ed1ab_0 couldn't be validated due to runtime error: Could not set URL (code: 14 - url = /certifi-2023.5.7-pyhd8ed1ab_0.conda)
warning  libmamba Could not validate package '/opt/miniconda/pkgs/certifi-2023.5.7-pyhd8ed1ab_0.conda': md5 and sha256 sum unknown.
    Set safety_checks to disabled to override this warning.
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "/opt/miniconda/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.11/site-packages/conda_env/cli/main.py", line 49, in do_call
        exit_code = getattr(module, func_name)(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.11/site-packages/conda/notices/core.py", line 123, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.11/site-packages/conda_env/cli/main_update.py", line 139, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.11/site-packages/mamba/mamba_env.py", line 169, in mamba_install
        conda_transaction = to_txn(
                            ^^^^^^^
      File "/opt/miniconda/lib/python3.11/site-packages/mamba/utils.py", line 464, in to_txn
        final_precs = compute_final_precs(
                      ^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.11/site-packages/mamba/utils.py", line 410, in compute_final_precs
        raise ValueError("missing key {} in channels: {}".format(key, lookup_dict))
    ValueError: missing key https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda in channels: {'https://repo.anaconda.com/pkgs/main/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/main/linux-64', 'channel': pkgs/main[linux-64,noarch], 'needs_finalising': True}, 'https://repo.anaconda.com/pkgs/main/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/main/noarch', 'channel': pkgs/main[linux-64,noarch], 'needs_finalising': True}, 'https://repo.anaconda.com/pkgs/r/linux-64': {'platform': 'linux-64', 'url': 'https://repo.anaconda.com/pkgs/r/linux-64', 'channel': pkgs/r[linux-64,noarch], 'needs_finalising': True}, 'https://repo.anaconda.com/pkgs/r/noarch': {'platform': 'noarch', 'url': 'https://repo.anaconda.com/pkgs/r/noarch', 'channel': pkgs/r[linux-64,noarch], 'needs_finalising': True}, 'https://conda.anaconda.org/conda-forge/linux-64': {'platform': 'linux-64', 'url': 'https://conda.anaconda.org/conda-forge/linux-64', 'channel': conda-forge[linux-64,noarch], 'needs_finalising': False}, 'https://conda.anaconda.org/conda-forge/noarch': {'platform': 'noarch', 'url': 'https://conda.anaconda.org/conda-forge/noarch', 'channel': conda-forge[linux-64,noarch], 'needs_finalising': False}, 'https://conda.anaconda.org/pytorch/linux-64': {'platform': 'linux-64', 'url': 'https://conda.anaconda.org/pytorch/linux-64', 'channel': pytorch[linux-64,noarch], 'needs_finalising': True}, 'https://conda.anaconda.org/pytorch/noarch': {'platform': 'noarch', 'url': 'https://conda.anaconda.org/pytorch/noarch', 'channel': pytorch[linux-64,noarch], 'needs_finalising': True}}
`$ /opt/miniconda/condabin/mamba update -q -n base -f environment.yml`
  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
                CONDA_DIR=/opt/miniconda
                CONDA_EXE=/opt/miniconda/bin/conda
         CONDA_PYTHON_EXE=/opt/miniconda/bin/python
               CONDA_ROOT=/opt/miniconda
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/miniconda/condabin:/home/uxavuc_user/bin:/opt/miniconda/bin:/home
                          /uxavuc_user/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/
                          sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
     active environment : None
            shell level : 0
       user config file : /home/uxavuc_user/.condarc
 populated config files : 
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/miniconda  (writable)
      conda av data dir : /opt/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda/pkgs
                          /home/uxavuc_user/.conda/pkgs
       envs directories : /opt/miniconda/envs
                          /home/uxavuc_user/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Linux/5.15.0-76-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1009:1009
             netrc file : None
           offline mode : False
An unexpected error has occurred. Conda has prepared the above report.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

### mamba info / micromamba info

```shell
mamba version : 1.4.9
     active environment : None
            shell level : 0
       user config file : /home/uxavuc_user/.condarc
 populated config files : 
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/miniconda  (writable)
      conda av data dir : /opt/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda/pkgs
                          /home/uxavuc_user/.conda/pkgs
       envs directories : /opt/miniconda/envs
                          /home/uxavuc_user/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Linux/5.15.0-76-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1009:1009
             netrc file : None
           offline mode : False
```

### environment.yml

```yaml
name: uxavuc
channels:
  - defaults
  - conda-forge
  - pytorch
  # - apple # only necessary for apple silicon
dependencies:
  - _openmp_mutex=*=*_gnu
  - black
  - click # Necessary for experiment_cli
  - flake8
  - hypothesis # Better intergration tests
  - ipykernel
  - lime
  - loguru
  - matplotlib
  - mlflow # Tracking machine learning experiments
  - numpy
  - openpyxl
  - openssl
  - optuna
  - pandas
  - paramiko
  - pip
  - pre-commit # Pre commit hooks, used for black & flake8 checking
  - PyJWT
  - pytest
  - python-dotenv
  - python=3.10
  - pyyaml
  - scikit-learn
  - seaborn
  - shap
  - toolz
  - treelib
  - umap-learn
  - xlsxwriter
  # - tensorflow-deps # only necessary for apple silicon
  - pip:
      - kaleido
      - dvc-s3
      - dvc-ssh
      - dvc==2.34.0
      - packaging
      - pytest-watch # For automated re-execution of tests
      - tensorflow==2.9.0; sys_platform!="darwin" or platform_machine != 'arm64'
      - tensorflow-probability==0.17.0 # this release is specifically tailored to the TF 2.9.0 to shut down the warning

      # Apple Silicon Specific stuff (without Rosetta)
      - tensorflow-macos==2.9.0; sys_platform == 'darwin' and platform_machine == 'arm64'
      - tensorflow-metal==0.5; sys_platform == 'darwin' and platform_machine == 'arm64'

      # PyTorch
      - torchmetrics
      - torch==1.13.0
      - torchvision==0.14
      - torchaudio==0.13


      - kubernetes # To trigger CLI commands in deployed webapi
      - requests
      - urllib3 # Necessary to configure mlflow server communication
      - wfdb==3.4.0

      # Dependencies for dashy / reporting
      - bokeh==2.4.2
      - cachetools==5.0.0
      - dash_bootstrap_components
      - dash-bootstrap-components==1.1.0
      - dash==2.4.1
      - feather-format==0.4.1
      - feather-format==0.4.1
      - Flask-Caching
      - flask-caching==1.10.1
      - flask==2.1.2
      - holoviews
      - hvplot
      - jupyter-bokeh==3.0.3 # Keep this before holoviews
      - jupytext
      - plotly==5.8.0
      - pyarrow==8.0.0
      - types-cachetools==5.2.1
      - dash_defer_js_import
      # Dependencies for documentation
      - m2r2
      - nbsphinx
      - sphinx
      - sphinx-autodoc-typehints
      - sphinx-typlog-theme
      - sphinxcontrib-plantuml

      # Install Packages:
      - setuptools
      - setuptools-cpp

  # NOTE: The package must be installed from here, due to setup.py can only be installed
  # from https://pypi.org/project/nodejs/ and there is no version 14 in it yet.
  - nodejs>=16

  # NOTE: We enforce a version >1, since conda would otherwise prefer a rather old
  # version in the defaults channel.
  # NOTE: The package must be installed from here, due to setup.py can only be installed
  # from https://pypi.org/project/yarn/ and there is no version >1 in it yet.
  - yarn>1
```
