### ISSUE TITLE
Some headers not resolved by cmake

### ISSUE THREAD

**Issue by cvanelteren** [mamba-org/mamba#2694]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

solv 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

hi all,

I am trying to build libmamba from source but facing some issues with some headers not being resolved properly. 

# Steps
1. Install micromamba : `yay micromba-bin`
2. Create environment: `micromamba create env --name mamba-dev`
3. Update environment: `micromamba install --name mamba-dev --file libmamba/environment-dev.yml` (from mamba root)
4. Run cmake  
 ```
cmake -B build/ \
    -DBUILD_LIBMAMBA=ON \
    -DBUILD_SHARED=ON \
    -DBUILD_LIBMAMBA_TESTS=ON
cmake --build build/
```

Now I can see that the headers are present in the root prefix, that is

```
❯ ls ~/micromamba/envs/mamba-dev/include/solv*
bitmap.h        evr.h      poolarch.h    queue.h       repodata.h     solver.h       tools_util.h
chksum.h        hash.h     poolid.h      repo.h        rules.h        solverdebug.h  transaction.h
conda.h         knownid.h  pooltypes.h   repo_conda.h  selection.h    solvversion.h  util.h
dataiterator.h  policy.h   poolvendor.h  repo_solv.h   solv_xfopen.h  strpool.h
dirpool.h       pool.h     problems.h    repo_write.h  solvable.h     testcase.h
```

### mamba info / micromamba info

```shell
libmamba version : 1.4.9
     micromamba version : 1.4.9
           curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /home/casper/micromamba/envs
          package cache : /home/casper/micromamba/pkgs
                          /home/casper/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /home/casper/.mambarc
 populated config files : /home/casper/.condarc
       virtual packages : __unix=0=0
                          __linux=6.4.3=0
                          __glibc=2.37=0
                          __archspec=1=x86_64
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
       base environment : /home/casper/micromamba
               platform : linux-64
```

### Logs

```shell
In file included from /home/casper/projects/mamba/libmamba/src/solv-cpp/queue.cpp:16:
/home/casper/projects/mamba/libmamba/src/solv-cpp/queue.hpp:13:10: fatal error: solv/queue.h: No such file or directory
   13 | #include <solv/queue.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libmamba/CMakeFiles/libmamba-static.dir/build.make:138: libmamba/CMakeFiles/libmamba-static.dir/src/solv-cpp/queue.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: libmamba/CMakeFiles/libmamba-static.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### environment.yml

```yaml
name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake >=3.16
  - ninja
  - nlohmann_json
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl >=7.86
  - doctest
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - cli11 >=2.2
  - spdlog
  - fmt
  - sel(win): winreg
~                                                                                                           
~
```

### ~/.condarc

```yaml
channels:
  - conda-forge
  - defaults
auto_activate_base: false
solver: classic
```
