### ISSUE TITLE
refer dependencies from separate file _directly_ from environment.yml

### ISSUE THREAD

**Issue by goyalyashpal** [mamba-org/mamba#2700]
## Update:
**2023-08-09**
Even if it were not for interoperability with `pip` (pypi repo), that is, even if the file would have to contain conda-forge specific names, this ability would still help:

* in interpo with package managers using conda-forge\
e.g. `mamba install --update-all --file` as `mamba` has no support env.yml file for installs it seems
\[ ref: https://github.com/mamba-org/mamba/issues/2700#issuecomment-1652511362 ]

* in specifying additional packages required for development, as a single commentable line
as there's currently no provision of `optional` field in env.yml files 
\[ ref: https://github.com/conda/conda/issues/12098 ]

* in jumping quickly from dev env to user environment via `prune-to-specs`: 
\[ https://github.com/mamba-org/mamba/issues/1455#issuecomment-1032754684 ]

### Known to work
The environment.yml file allows specifying `-r requirements.txt` as a subdependency of pip. 
As shown in following example (based on answers given at [this SO question][35245401/#35245610])

[35245401/#35245610]: https://stackoverflow.com/questions/35245401/#35245610 "combining-conda-environment-yml-with-pip-requirements-txt"

```yml
name: test-env
dependencies:
  - python>=3.5
  - pip
  - pip:
    - -r requirements.txt
    - <hyperlink to .whl>
    - <normal package name>
# prefix: "$USERPROFILE"/.../envs/myenv
```

### Question

but is there a way to specify the requirements.txt file as a direct dependency? this will allow one to use whichever method is available at one's disposal.

this will also allow to quickly swap the file from say `requirement-directly-pinned.txt` (directly used deps locked) to `requirements-transitively-pinned.txt` (all deps locked).

i am thinking something like this:

```yml
name: test-env
dependencies:
  - python>=3.5
  - requirements-directly-pinned.txt
```

### Reason Behind

* I use `micromamba` on my local windows PC with unix tools from msys2, 
* `pip` on github codespaces (ubuntu based devcontainer) - i tried to use `mamba` there, that overpowered the 32 GB disk space provided
* my coworked also use `pip` on their local windows PC
