### ISSUE TITLE
`failed to create process.` while directly running packages which are installed from micromamba

### ISSUE THREAD

**Issue by goyalyashpal** [mamba-org/mamba#2702]
Jump to https://github.com/mamba-org/mamba/issues/2702#issuecomment-1652409499 for conclusion.

<details><summary>Head</summary>

### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

[run subprocess](https://github.com/mamba-org/mamba/issues?q=is%3Aissue+is%3Aopen+run+subprocess)

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

</details> 

### Describe your issue

On installing run-able packages from micromamba, it shows the error `failed to create process.` 
run-able packages which can be invoked on their own: tried with `conda-lock` & `flet`

maybe following issues seem similar:
* https://github.com/mamba-org/mamba/issues/1396
* https://github.com/mamba-org/mamba/issues/1467

P.S. the issue template is super awesome: [bug.yml](https://github.com/mamba-org/mamba/blob/0e2deaf/.github/ISSUE_TEMPLATE/bug.yml)

<details><summary>Tail</summary>

### mamba info / micromamba info

```shell
       libmamba version : 1.4.9
     micromamba version : 1.4.9
           curl version : libcurl/8.1.2-DEV Schannel zlib/1.2.13
     libarchive version : libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.3 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.5
       envs directories : C:\Users\...\micromamba\envs
          package cache : C:\Users\...\micromamba\pkgs
                          C:\Users\...\.mamba\pkgs
                          C:\Users\...\AppData\Roaming\.mamba\pkgs
            environment : facerecog_env (active)
           env location : C:\Users\...\micromamba\envs\facerecog_env
      user config files : C:\Users\...\.mambarc
 populated config files : C:\Users\...\micromamba\.mambarc
       virtual packages : __win=0=0
                          __archspec=1=x86_64
                          __cuda=10.2=0
               channels : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : C:\Users\<user>\micromamba
               platform : win-64
```

### Logs

```shell
$ conda-lock --help
failed to create process.

$ flet -r ./
failed to create process.

$ micromamba -v run flet -r ./
failed to create process.

$ micromamba -v run --env flet -r ./
error    libmamba Did not receive any command to run inside environment
```

### environment.yml

```yaml
name: facerecog_env
channels:
  - conda-forge
dependencies:
  # Use foll to decide versions for adding new packages
  # mamba repoquery search <pkg>
  # mamba --dry-run install <pkg>
  #
  # If it's not the latest one, then try with latest one
  # to see what existing pkg would break
  #
  # Like in my case, it opt flet 0.7.4 against 0.8.0 to save pydantic
  # Obviously pydantic is a small pkg, whereas flet 0.7.4 would be
  # an instant legacy code.
  #
  # mamba --dry-run install <pkg>==<ver>
  #
  # - python >=3.6,<3.7
  - python >=3.11
  - face-recognition==1.3.0
  - numpy==1.25.1
  - opencv==4.7.0
  # - dlib==19.24.2
  # - face_recognition_models==0.3.0
  # - Pillow==10.0.0
  - loguru
  - filetype==1.2.0
  - flet==0.8.2
# prefix: "$USERPROFILE"/.../envs/
```

### ~/.condarc

```yaml
# $ cat "$USERPROFILE/micromamba/.mambarc"
channels:
  - conda-forge
always_yes: false(facerecog_env)
```

</details>
