### ISSUE TITLE
Uncertain if it is a mamba issue - GitHub Action can use mamba to build regular projects but fails to build in Docker

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [mamba-org/mamba#2716]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

GitHub Action Docker

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

The warning messages I get are similar to those reported in this issue: https://github.com/mamba-org/mamba/issues/2666
But that issue does not say it is running in GitHub Action for building a Docker image.

At this point, I am not even sure if it is a mamba issue because other actions that also use mamba successfully builds the environment. However, the Docker attempt fails. The detailed message can be found here, if anyone can take a look and even give a definitive call on whether if this is a mamba issue that would be appreciated:

https://github.com/lanl/MILK/actions/runs/5682341983/job/15400502594

### mamba info / micromamba info

```shell
mamba command is not found when attempted to execute `mamba info`. It seems the GitHub action docker build automatically uses mamba.
```

### Logs

```shell
Unable to provide, since it is built-in with the docker build.
```

### environment.yml

```yaml
name: rietveld

channels:
  - defaults
  - conda-forge
  
dependencies:
  #Base MILK
  - tqdm
  - pip=22.1.2
  - prettytable
  - python=3.9
  - pandas
  - pydantic
  - seaborn
  - pyfai
  - matplotlib
  - pyopencl
  - opencv
  - pyqtgraph
  - autopep8
  - git
  - pytest
  
  # Spotlight
  - klepto=0.2.2
  - numpy=1.23.0
  # - openmpi
  # - mpi4py
  - jupyter=1.0.0
  - nbsphinx=0.8.9
  - sphinx=5.0.2
  - sphinxcontrib-programoutput=0.16
  - scipy=1.8.1
  - scikit-learn=1.1.2

  # pip packages
  - pip:
    #MILK github installation
    - -e ../
    #Spotlight
    - git+https://github.com/lanl/spotlight.git@v0.10.2
    - mystic==0.4.1
    - pyina==0.2.8
    - pathos==0.3.1
```

### ~/.condarc

```yaml
Unable to retrieve this information from GitHub docker action.
```
