### ISSUE TITLE
segfault on github-actions with ciao repo

### ISSUE THREAD

**Issue by JohannesBuchner** [mamba-org/mamba#2930]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

segfault

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I get a segfault with the following command:
```
mamba create -y -n ciao --override-channels -c https://cxc.cfa.harvard.edu/conda/ciao -c conda-forge ciao sherpa ds9 ciao-contrib caldb_main astropy "matplotlib>=3.5" ultranest coverage coveralls scipy h5py astropy requests cython tqdm coverage toml
```

I installed via mambaforge on github-actions, where I get version 1.4.2, with:

```
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          channel-priority: strict
          python-version: 3.11
          use-mamba: true
          use-only-tar-bz2: false # IMPORTANT: This may break caching of conda packages! See https://github.com/conda-incubator/setup-miniconda/issues/267
```

https://github.com/JohannesBuchner/BXA/actions/runs/6602627753/workflow

### mamba info / micromamba info

```shell
1.4.2
```

### Logs

```shell
https://github.com/JohannesBuchner/BXA/actions/runs/6602627753/job/17934886680
```

### environment.yml

```yaml
https://github.com/JohannesBuchner/BXA/actions/runs/6602627753/workflow
```

### ~/.condarc

```yaml
N/A
```
