### ISSUE TITLE
Package ordering and duplication substantially affects solve times

### ISSUE THREAD

**Issue by vyasr** [mamba-org/mamba#3058]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

is:issue slow order; is:issue order; is:issue solve order

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I have an environment where the time to solve is very slow, and oddly is dramatically different based on the order in which packages are specified (see the env file pasted below). Moving shapely and pydeck to the end of the environment list has a dramatic reduction in the solve time (from ~400 seconds to ~80 seconds). I originally had a much larger environment but whittled it down to this minimal one a couple of days ago. Unfortunately, when I tried the same thing today the solve has become very fast, so I'm guessing that a new package release has made it much easier for the solver to converge quickly. 

I realize that since mamba using a backtracking solver order-dependence is to be expected, so there may not be much that can be done here. One minor suggestion might be to sort and deduplicate the dependency list for the sake of predictability (while reducing the file down I also found that duplicates could also have odd behaviors, again depending on the ordering of those duplicates relative to other dependencies in the list).

I marked this problem as N/A for the "Tried in conda" dropdown above because the conda solve never converged in either case, so I couldn't get useful metrics (that was without the new libmamba solver, and unfortunately I didn't think to try the libmamba solver until today when the mamba issues also seem to have vanished). I also did not try forcing strict channel priority (my default is currently flexible).

### mamba info / micromamba info

```shell
mamba version : 1.5.4
     active environment : main
    active env location : /home/vyasr/miniconda3/envs/main
            shell level : 1
       user config file : /home/vyasr/.condarc
 populated config files : /home/vyasr/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.9.15.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=23.11.0=0
                          __cuda=12.2=0
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/vyasr/miniconda3  (writable)
      conda av data dir : /home/vyasr/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : 
          package cache : /home/vyasr/miniconda3/pkgs
                          /home/vyasr/.conda/pkgs
       envs directories : /home/vyasr/miniconda3/envs
                          /home/vyasr/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.28.1 CPython/3.9.15 Linux/6.2.0-35-generic ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.4
                UID:GID : 1000:1000
             netrc file : /home/vyasr/.netrc
           offline mode : False
```

### environment.yml

```yaml
channels:                                                                                                                                                                                                 
  - pytorch                                                                                                                                                                                                 
  - conda-forge                                                                                                                                                                                             
  dependencies:                                                                                                                                                                                             
  - c-compiler                                                                                                                                                                                              
  - cmake>=3.26.4                                                                                                                                                                                           
  - cxx-compiler                                                                                                                                                                                            
  - dlpack>=0.5,<0.6.0a0                                                                                                                                                                                    
  - fmt>=10.1.1,<11                                                                                                                                                                                         
  - geopandas>=0.11.0                                                                                                                                                                                       
  - libparquet==14.0.1.*                                                                                                                                                                                    
  - msgpack-python                                                                                                                                                                                          
  - proj                                                                                                                                                                                                    
  - protobuf>=4.21,<5                                                                                                                                                                                       
  - pydeck                                                                                                                                                                                                  
  - pytorch<1.12.0                                                                                                                                                                                          
  - shapely                                                                                                                                                                                                 
  - spdlog>=1.12.0,<1.13
```

### ~/.condarc

```yaml
auto_activate_base: false
channels: []
channel_priority: flexible
```
