### ISSUE TITLE
Micromamba struggles with nonstandard platforms

### ISSUE THREAD

**Issue by calebzulawski** [mamba-org/mamba#3187]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

platform

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

Micromamba struggles to interpret non-standard platforms/subdirs and adds an extra unrelated subdir into download URLS.  This happens even with explicit envs that contain the correct URL

### Logs

```shell
critical libmamba Multi-download failed. Reason: Transfer finalized, status: 404 [https://company-internal.com/artifactory/api/conda/my-channel/linux-64-foo/linux-64/package-1.0.0-hXXXXXXX.tar.bz2] 88 bytes
```

### environment.yml

```yaml
# Generated by conda-lock.
# platform: linux-64-foo
# input_hash: some hash
@EXPLICIT
https://company-internal.com/artifactory/api/conda/my-channel/linux-64-foo/package-1.0.0-hXXXXXXX.tar.bz2#hash
```

### ~/.condarc

```yaml
default_channels: [https://company-internal.com/artifactory/api/conda/my-channel]
channels: [defaults]
platform: linux-64-foo
```
