### ISSUE TITLE
Fresh Windows installation miniforge "mamba is not recognized"

### ISSUE THREAD

**Issue by GrigoriiTarasov** [mamba-org/mamba#3200]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

not recognized

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Fresh WIndows 10, Fresh install of latest miniconda form https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html

in miniconda prompt

```
>mamba env list
'mamba' is not recognized as an internal or external command,
operable program or batch file.

```

So really how to start use mamba in suck installation? How to install mamba in miniforge if it needed? How to make it visible for git bash?

### ~/.condarc

```yaml
In miniforge prompt:

cat ~/.condarc
'cat' is not recognized as an internal or external command,
operable program or batch file.

In git bash:
cat ~/.condarc
channels:
  - defaults
  - conda-forge
```
