### ISSUE TITLE
[micromamba] environment variables in condarc only resolved when using curly brackets

### ISSUE THREAD

**Issue by skwde** [mamba-org/mamba#3288]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

environment variables

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

This is a followup to #1393 where support for env variables was added.

Though the env variables need to be enclosed with curly brackets, e.g. ${HOME} works while $HOME does not.

It works with `conda` and `mamba`.

### mamba info / micromamba info

```shell
libmamba version : 1.5.8
     micromamba version : 1.5.8
           curl version : libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.58.0
     libarchive version : libarchive 3.5.3 zlib/1.2.12 liblzma/5.4.3 bz2lib/1.0.8
       envs directories : ~/.conda/envs
          package cache : ~/.conda/pkgs
            environment : None (not found)
           env location : -
      user config files : ~.mambarc
 populated config files : ~/.condarc
       virtual packages : __unix=0=0
                          __osx=14.4.1=0
                          __archspec=1=x86_64-v3
               channels : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/osx-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : ~/.conda
               platform : osx-64
```

### ~/.condarc

```yaml
---
channel_priority: strict

channels:
  - conda-forge
  - nodefaults

env_prompt: '({default_env}) '

auto_activate_base: false

pkgs_dirs:
  - "$HOME/.conda/pkgs"

envs_dirs:
  - "$HOME/.conda/envs"
```
