### ISSUE TITLE
 solver_addrule: Assertion `!p2 && d > 0' failed

### ISSUE THREAD

**Issue by holzman** [mamba-org/mamba#3290]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

Similar to #1382, but for a single (conda-forge) channel

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

Trying to create an environment from environment.yaml below runs for a long time, and eventually gives:
```solver_addrule: Assertion `!p2 && d > 0' failed```

This is for non-CUDA installs, so to reproduce you may need to set `CONDA_OVERRIDE_CUDA` to `""`.
I was able to get the same error with a subset of the packages:

```mamba create -n test -C 'awkward<2' 'bokeh' 'brotli' 'ca-policy-lcg' 'coffea=0.7.22' 'correctionlib' 'curl' 'dask-expr' 'dask-gateway' 'dask-jobqueue' 'dask_labextension' 'geventhttpclient' 'gxx' 'h5py' 'hist' 'htcondor' 'ipympl' 'pytorch_spline_conv'```

If I reduce further, it does eventually solve, but takes a surprisingly long time (more than an hour):

```mamba create -n test -C 'awkward<2' 'bokeh' 'brotli' 'ca-policy-lcg' 'curl' 'dask-expr' 'pytorch_spline_conv'```

### mamba info / micromamba info

```shell
mamba version : 1.5.8
     active environment : base
    active env location : /storage/local/data1/home/burt/miniforge3
            shell level : 1
       user config file : /storage/local/data1/home/burt/.condarc
 populated config files : /storage/local/data1/home/burt/miniforge3/.condarc
                          /storage/local/data1/home/burt/.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.3.0=0
                          __glibc=2.34=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /storage/local/data1/home/burt/miniforge3  (writable)
      conda av data dir : /storage/local/data1/home/burt/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /storage/local/data1/home/burt/miniforge3/pkgs
                          /storage/local/data1/home/burt/.conda/pkgs
       envs directories : /storage/local/data1/home/burt/miniforge3/envs
                          /storage/local/data1/home/burt/.conda/envs
               platform : linux-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Linux/5.14.0-362.13.1.el9_3.x86_64 almalinux/9.3 glibc/2.34 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.4.2
                UID:GID : 12697:5063
             netrc file : None
           offline mode : False
```

### Logs

```shell
Looking for: ["awkward[version='<2']", 'bokeh', 'brotli', 'ca-policy-lcg', 'coffea=0.7.22', 'correctionlib', 'curl', 'dask-expr', 'dask-gateway', 'dask-jobqueue', 'dask_labextension', 'geventhttpclient', 'gxx', 'h5py', 'hist', 'htcondor', 'ipympl', 'pytorch_spline_conv']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
python: /home/conda/feedstock_root/build_artifacts/libsolv-split_1711552982341/work/src/rules.c:261: solver_addrule: Assertion `!p2 && d > 0' failed.
```

### environment.yml

```yaml
name: test1
channels:
  - conda-forge
dependencies:
  - awkward<2
  - bokeh
  - brotli
  - ca-policy-lcg
  - coffea=0.7.22
  - correctionlib
  - curl
  - dask-expr
  - dask-gateway
  - dask-jobqueue
  - dask_labextension
  - geventhttpclient
  - gxx
  - h5py
  - hist
  - htcondor
  - ipympl
  - jupyterlab
  - lz4
  - ndcctools
  - numpy
  - onnxruntime
  - pandas
  - pip
  - pytables
  - python-graphviz
  - python-rapidjson
  - python-xxhash
  - pytorch
  - pytorch_cluster
  - pytorch_sparse
  - pytorch_spline_conv
  - rucio-clients
  - scipy
  - torch-scatter
  - uproot<5
  - vector
```

### ~/.condarc

```yaml
channels:
  - conda-forge
auto_activate_base: false
```
