### ISSUE TITLE
Use uv package manager for installing packages from PyPI

### ISSUE THREAD

**Issue by awvwgk** [mamba-org/mamba#3332]
Does mamba have the possibility to install packages from PyPI via [uv](https://github.com/astral-sh/uv) instead pip?

**Comment by Lumcoin** [comment]
Maybe uv has any drawbacks? It does feel odd that "mamba env create" takes forever to install pip dependencies, while uv does it within seconds...

**Comment by sidmadala** [comment]
Will the integration of `uv` allow for `environment.yaml` files like this?

```yaml
name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - nvidia::cuda-toolkit=12.4
  - uv
  - uv:  # Use uv for all other packages
    - torch>=2.5.0
...
```
