### ISSUE TITLE
mamba show more hidden which cause I don‘t know whether the progress is stuck

### ISSUE THREAD

**Issue by vipcxj** [mamba-org/mamba#3444]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

more hidden

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

After a long wait, the dependency is finally downloaded, and then it enters the unzipping and installation stage, and Mamba shows a whole bunch of progress bars at once. But in the last line, it shows that:
``` ... (more hidden) ...```
When this large number of progress bars are 100%, the console output is no longer changed. I can't tell if it's malfunctioning, stuck there, or if the installation is still going on. I've been waiting for an hour and can't tell if it's ctrl-c to try again or keep waiting

### mamba info / micromamba info

```shell
__    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : comic-text-detector
    active env location : C:\Users\vipcx\mambaforge\envs\comic-text-detector
            shell level : 1
       user config file : C:\Users\vipcx\.condarc
 populated config files : C:\Users\vipcx\mambaforge\.condarc
                          C:\Users\vipcx\.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.6=0
                          __win=0=0
       base environment : C:\Users\vipcx\mambaforge  (writable)
      conda av data dir : C:\Users\vipcx\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch
          package cache : C:\Users\vipcx\mambaforge\pkgs
                          C:\Users\vipcx\.conda\pkgs
                          C:\Users\vipcx\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\vipcx\mambaforge\envs
                          C:\Users\vipcx\.conda\envs
                          C:\Users\vipcx\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Windows/10 Windows/10.0.22631
          administrator : False
             netrc file : None
           offline mode : False
```

### ~/.condarc

```yaml
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.bfsu.edu.cn/anaconda/cloud
  msys2: https://mirrors.bfsu.edu.cn/anaconda/cloud
  bioconda: https://mirrors.bfsu.edu.cn/anaconda/cloud
  menpo: https://mirrors.bfsu.edu.cn/anaconda/cloud
  pytorch: https://mirrors.bfsu.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.bfsu.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.bfsu.edu.cn/anaconda/cloud
  nvidia: https://mirrors.sustech.edu.cn/anaconda-extra/cloud
```
