### ISSUE TITLE
Micromamba v2.0 unable to parse environment.yml

### ISSUE THREAD

**Issue by breakbotz** [mamba-org/mamba#3472]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

Creating issue as recommended in https://github.com/mamba-org/micromamba-releases/issues/58

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

A unit test in my GitHub Actions pipeline is failing when attempting to create a micromamba environment using an environment.yaml which has not changed in months.

Using the latest version (curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest), we run `micromamba env create --yes --file environment.yml` which errors with `libmamba Could not solve for environment specs`. More detailed error logs provided below and full output can be found in my [GHA pipeline run](https://github.com/BCG-X-Official/artkit/actions/runs/11044431820/job/30680379445).

### Logs

```shell
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ aiohttp ~= does not exist (perhaps a typo or a missing channel);
    ├─ anthropic ~= does not exist (perhaps a typo or a missing channel);
    ├─ fluxus ~= does not exist (perhaps a typo or a missing channel);
    ├─ gamma-pytools ~= does not exist (perhaps a typo or a missing channel);
    ├─ google-generativeai ~= does not exist (perhaps a typo or a missing channel);
    ├─ graphviz ~= does not exist (perhaps a typo or a missing channel);
    ├─ groq ~= does not exist (perhaps a typo or a missing channel);
    ├─ ipywidgets ~= does not exist (perhaps a typo or a missing channel);
    ├─ jupyterlab ~= does not exist (perhaps a typo or a missing channel);
    ├─ nbsphinx ~= does not exist (perhaps a typo or a missing channel);
    ├─ notebook ~= does not exist (perhaps a typo or a missing channel);
    ├─ openai ~= does not exist (perhaps a typo or a missing channel);
    ├─ packaging ~= does not exist (perhaps a typo or a missing channel);
    ├─ pandas ~= does not exist (perhaps a typo or a missing channel);
    ├─ pre-commit ~= does not exist (perhaps a typo or a missing channel);
    ├─ pytest-asyncio ~= does not exist (perhaps a typo or a missing channel);
    ├─ pytest-cov ~= does not exist (perhaps a typo or a missing channel);
    ├─ pytest ~= does not exist (perhaps a typo or a missing channel);
    ├─ python-dotenv ~= does not exist (perhaps a typo or a missing channel);
    ├─ python-graphviz ~= does not exist (perhaps a typo or a missing channel);
    ├─ pytorch ~= does not exist (perhaps a typo or a missing channel);
    ├─ sphinx-autodoc-typehints ~= does not exist (perhaps a typo or a missing channel);
    ├─ sphinx ~= does not exist (perhaps a typo or a missing channel);
    └─ transformers ~= does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
Error: Process completed with exit code 1.
```

### environment.yml

```yaml
name: artkit
channels:
  - bcgx
  - conda-forge
  - defaults
dependencies:
  # Python
  - python                   ~= 3.10.14

  # Additional libraries
  - fluxus                   ~= 1.0
  - gamma-pytools            ~= 3.0
  - pandas                   ~= 2.2
  - python-dotenv            ~= 1.0
  - graphviz                 ~= 9.0
  - python-graphviz          ~= 0.20
  - boto3                    ~= 1.34.0
  - moto                     ~= 5.0.11

  # LLM provider packages:
  - openai                   ~= 1.34
  - groq                     ~= 0.9
  - anthropic                ~= 0.26
  - google-generativeai      ~= 0.6
  - google-cloud-aiplatform  ~= 1.62.0

  # The following are required for huggingface:
  - aiohttp                  ~= 3.9
  - pytorch                  ~= 2.3
  - transformers             ~= 4.41

  # Sphinx documentation build
  - nbsphinx                 ~= 0.9
  - sphinx                   ~= 7.2
  - sphinx-autodoc-typehints ~= 1.25
  - pydata-sphinx-theme      ~= 0.15.1
  - packaging                ~= 24.1

  # Notebooks
  - ipywidgets               ~= 8.1
  - jupyterlab               ~= 4.2
  - notebook                 ~= 7.2

  # DevOps
  - pytest                   ~= 8.2
  - pytest-asyncio           ~= 0.23
  - pytest-cov               ~= 5.0
  - pre-commit               ~= 3.7
```
