### ISSUE TITLE
`micromamba env` does not show any environments in v2.0.2 anymore, despite having lots of environments

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#3500]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

micromamba env

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

`micromamba env` does not show any environments, but I definitely have many present on my system.

```
~ via 🐍 v3.11.9 in ☸ aws (main) on ☁️  (us-east-1)
❯ micromamba env
```

I just installed v2.0.2, I don't think I had this issue with v1.5.10

### mamba info / micromamba info

```shell
❯ micromamba info

       libmamba version : 2.0.2
     micromamba version : 2.0.2
           curl version : libcurl/8.9.1 (OpenSSL/3.3.2) SecureTransport zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /Users/corneliusromer/micromamba/envs
          package cache : /Users/corneliusromer/micromamba/pkgs
                          /Users/corneliusromer/.mamba/pkgs
            environment : /opt/homebrew/Caskroom/miniforge/base (active)
           env location : /opt/homebrew/Caskroom/miniforge/base
      user config files : /Users/corneliusromer/.mambarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
                          /Users/corneliusromer/.mambarc
                          /Users/corneliusromer/.condarc
       virtual packages : __unix=0=0
                          __osx=15.0=0
                          __archspec=1=arm64
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/nodefaults/noarch
                          https://conda.anaconda.org/nodefaults/osx-arm64
       base environment : /Users/corneliusromer/micromamba
               platform : osx-arm64
```

### Logs

```shell
$ micromamba env -v


there's really nothing there, just empty output
```

### environment.yml

```yaml
NA
```

### ~/.condarc

```yaml
❯ cat ~/.condarc
always_yes: true
show_channel_urls: true
solver: libmamba
changeps1: False
channels:
  - bioconda
  - conda-forge
  - nodefaults
channel_priority: strict

~ via 🐍 v3.11.9 in ☸ aws (main) on ☁️  (us-east-1)
❯ cat ~/.mambarc
repodata_use_zst: true
channels:
- conda-forge
- bioconda
```
