### ISSUE TITLE
fail to install a package from a local build channel

### ISSUE THREAD

**Issue by GuyPozner** [mamba-org/mamba#3518]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

https://github.com/mamba-org/mamba/issues/1991

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

Using the latest micromamba container image micromamba version 2.0.2 fails to install from a local build channel.

Steps to reproduce:
1. create Dockerfile202
```Dockerfile
# Dockerfile202
FROM mambaorg/micromamba:2.0.2

USER root
COPY my-mod my-mod
RUN cd my-mod && \
    micromamba install -n base -y conda-build boa git -c conda-forge && \
    mkdir build && micromamba run -n base conda mambabuild . --output-folder ./build --no-test && \
    ls build
RUN cd my-mod && \
    micromamba install -n base -y ./build::hello-world
```
2. create Dockerfile1.5.9
```Dockerfile
# Dockerfile159
FROM mambaorg/micromamba:1.5.9

USER root
COPY my-mod my-mod
RUN cd my-mod && \
    micromamba install -n base -y conda-build boa git -c conda-forge && \
    mkdir build && micromamba run -n base conda mambabuild . --output-folder ./build --no-test && \
    ls build
RUN cd my-mod && \
    micromamba install -n base -y ./build::hello-world
```
3. create the meta.yaml
```yaml
# my-mod/conda.recipe/meta.yaml
package:
  name: hello-world
  version: 0.1.0

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - hello_world
  commands:
    - python -c "import hello_world; hello_world.hello()"

about:
  home: https://github.com/yourusername/hello-world
  license: MIT
  summary: A simple Hello World package
```
4. create setup.py
```python
# my-mod/setup.py
from setuptools import setup, find_packages

setup(
    name="hello-world",
    version="0.1.0",
    packages=find_packages(),
    entry_points={
        "console_scripts": [
            "hello-world=hello_world:hello",
        ],
    },
)
```
5. create hello world module
```python
# my-mod/hello_world/hello_world.py
def hello():
    print("Hello, World!")

if __name__ == "__main__":
    hello()
```
6. add `__init__.py` to `my-mod/hello_world/__init__.py`
7. run `docker build -f Dockerfile202 -t micromamba-repro .` to reproduce error.
8. run `docker build -f Dockerfile159 -t micromamba-repro-159 .` to see that it works with previous version.

### mamba info / micromamba info

```shell
libmamba version : 2.0.2
     micromamba version : 2.0.2
           curl version : libcurl/8.9.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=5.3.0=0
                          __glibc=2.36=0
                          __archspec=1=x86_64_v4
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-64
```

### Logs

```shell
Step 5/5 : RUN cd my-mod &&     micromamba install -n base -y ./build::hello-world
 ---> Running in b15f4e5e1cdc
warning  libmamba Cache file "/opt/conda/pkgs/cache/88ec62ec.json" was modified by another program
warning  libmamba Cache file "/opt/conda/pkgs/cache/eb045dd1.json" was modified by another program

Pinned packages:

  - python=3.12

error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ hello-world does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
The command '/usr/local/bin/_dockerfile_shell.sh cd my-mod &&     micromamba install -n base -y ./build::hello-world' returned a non-zero code: 1
```
