### ISSUE TITLE
2.0.3-0 breaks mamba-org/setup-micromamba@v2 GH Action

### ISSUE THREAD

**Issue by kmuehlbauer** [mamba-org/mamba#3576]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

no other issue found

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

With latest micromamba 2.0.3-0 our CI mamba-org/setup-micromamba@v2 GH Action stopped working.

See https://github.com/pydata/xarray/actions/runs/11704038363/job/32595639555

```
/home/runner/micromamba-bin/micromamba list -r /home/runner/micromamba -n xarray-tests
  critical libmamba could not load prefix data
Error: The process '/home/runner/micromamba-bin/micromamba' failed with exit code 1
```

### mamba info / micromamba info

```shell
/home/runner/micromamba-bin/micromamba info -r /home/runner/micromamba -n xarray-tests
  
         libmamba version : 2.0.3
       micromamba version : 2.0.3
             curl version : libcurl/8.10.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.64.0
       libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
         envs directories : /home/runner/micromamba/envs
            package cache : /home/runner/micromamba/pkgs
                            /home/runner/.mamba/pkgs
              environment : xarray-tests
             env location : /home/runner/micromamba/envs/xarray-tests
        user config files : /home/runner/.mambarc
   populated config files : /home/runner/work/_temp/setup-micromamba/.condarc
         virtual packages : __unix=0=0
                            __linux=6.5.0=0
                            __glibc=2.35=0
                            __archspec=1=x86_64_v3
                 channels : https://conda.anaconda.org/conda-forge/linux-64
                            https://conda.anaconda.org/conda-forge/noarch
         base environment : /home/runner/micromamba
                 platform : linux-64
```

### Logs

```shell
https://github.com/pydata/xarray/actions/runs/11704038363/job/32595639555
```

### environment.yml

```yaml
name: xarray-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiobotocore
  - array-api-strict
  - boto3
  - bottleneck
  - cartopy
  - cftime
  - dask-core
  - dask-expr # dask raises a deprecation warning without this, breaking doctests
  - distributed
  - flox
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - hypothesis
  - iris
  - lxml # Optional dep of pydap
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numba
  - numbagg
  - numexpr
  - numpy>=2
  - opt_einsum
  - packaging
  - pandas
  # - pint>=0.22
  - pip
  - pooch
  - pre-commit
  - pyarrow # pandas raises a deprecation warning without this, breaking doctests
  - pydap
  # start pydap server dependencies, can be removed if pydap-server is available
  - gunicorn
  - PasteDeploy
  - docopt-ng
  - Webob
  - Jinja2
  - beautifulsoup4
  # end pydap server dependencies
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pytest-timeout
  - rasterio
  - scipy
  - seaborn
  - sparse
  - toolz
  - typing_extensions
  - zarr
```

### ~/.condarc

```yaml
no input
```
