### ISSUE TITLE
mamba breaks environment constraints for full environment update

### ISSUE THREAD

**Issue by noragen** [mamba-org/mamba#3883]
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [x] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

done

### Latest version of Mamba

- [x] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

Updating the version from mamba breaks it.

mamba update --all

results in

![Image](https://github.com/user-attachments/assets/375d1956-a763-4d1b-b6e0-96e53fc75d96)

I was able to restore the working mamba installation and downdate it with 

conda update --all --solver=classic

### mamba info / micromamba info

```shell
not possible
```

### Logs

```shell

```

### environment.yml

```yaml

```

### ~/.condarc

```yaml
channels:
  - conda-forge
  - nodefaults
ssl_verify: true
pip_interop_enabled: true
report_errors: true
```
