### ISSUE TITLE
Mamba installs to wrong directory when executed from an activated environment

### ISSUE THREAD

**Issue by ericmjl** [mamba-org/mamba#447]
I think I have found a bug, but I am not sure, so I'm reporting it here to check first.

Let's say I have an environment, called `testenv`. I created it while in my `(base)` environment, and it contains mamba.

```bash
(base) $ conda create -n testenv python=3.8 mamba 
(base) $ conda activate testenv
(testenv) $
```

Now, within my `testenv`, I _update_ the environment from an environment.yml file:

```yaml
name: testenv
channels:
- conda-forge
dependencies:
- python=3.8.5
- jupyter=1.0.0
- conda
- ipython=7.15.0
- ipykernel=5.3.0
- jax=0.1.74
- jaxlib=0.1.52
- numpy=1.18.5
- matplotlib=3.2.2
- scipy=1.5.2
```

```bash
(testenv) $ mamba env update -f environment.yml
```

I noticed that mamba installs everything into the directory `/path/to/anaconda/envs/testenv/envs/testenv/`.

This shouldn't be the case, I think it should install to `/path/to/anaconda/envs/testenv` instead.

Would I be incorrect in saying that this is a bug, or is this intended behaviour, such that mamba should never be installed in a `conda` environment, and only remain in the base?
