### ISSUE TITLE
mamba fails to install env which conda can install

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#517]
On linux-64 the below environment can be installed with `conda` but `mamba` gives a nonsensical error:
(I've ported the package to an env file to more easily test outside CI , but it should be the same)
```
Encountered problems while solving.
Problem: package kitchen-sink-0.1.1.post008+9437065-0 requires yellowbrick >=1.1, but none of the providers can be installed
```
The error is nonsensical because the package *does* exist on conda-forge:
```
Loading channels: done
# Name                       Version           Build  Channel
yellowbrick                      1.1    pyh9f0ad1d_0  conda-forge
```

<details>
<summary><b><tt>environment.yml</tt></b></summary>

```yaml
name: kitchen_sink

channels:
  - conda-forge
  - defaults
  - fastai
  - pytorch

dependencies:
  - python =3.7.*
  - adlfs                                  >=0.4.0
  - altair                                 >=4.1.0
  - arviz                                  >=0.9.0
  - astropy                                >=4.0.1
  - atomicwrites                           >=1.4.0
  - beautifulsoup4                         >=4.9.1
  - bitarray                               >=1.5.3
  - black                                  >=19.10b0
  - blosc                                  >=1.20.0
  - bokeh                                  >=2.2.0
  - bottleneck                             >=1.3.2
  - bzip2                                  >=1.0.8
  - cachetools                             >=4.1.1
  - catboost                               >=0.24
  - cffi                                   >=1.14.1
  - chardet                                >=3.0.4
  - click                                  >=7.1.2
  - cloudpickle                            >=1.6.0
  - colorama                               >=0.4.3
  - colorcet                               >=2.0.1
  - configobj                              >=5.0.6
  - coverage                               >=5.2.1
  - cryptography                           >=3.1
  - curl                                   >=7.71.1
  - cx_oracle                              >=8.0
  - cyipopt                                >=0.2.0
  - cython                                 >=0.29.21
  - cytoolz                                >=0.10.1
  - dabl                                   >=0.1.8
  - dask                                   >=2.24.0
  - dask-ml                                >=1.6.0
  - datashader                             >=0.11.1
  - decorator                              >=4.4.2
  - defaults::libblas * *mkl
  - defaults::mkl                          >=2020.2
  - defaults::mkl_fft                      >=1.1.0
  - defaults::mkl_random                   >=1.1.1
  - defaults::mkl-service                  >=2.3
  - defaults::numpy                        >=1.18
  - defaults::scikit-learn                 >=0.23
  - defaults::scipy                        >=1.5.2
  - defaults::tbb                          >=2020.2
  - defaults::tensorflow                   >=2.2.0
  - distributed                            >=2.24.0
  - docutils                               >=0.16
  - exchangelib                            >=3.2.1
  - factory_boy                            >=3.0.1
  - fastai                                 >=2.0.0
  - fastapi                                >=0.61.0
  - fbprophet                              >=0.6
  - flask                                  >=1.1.2
  - flask-cors                             >=3.0.8
  - fletcher                               >=0.5.0
  - fsspec                                 >=0.8.0
  - graphviz                               >=2.38.0
  - h5py                                   >=2.10
  - hdf4                                   >=4.2.13
  - hdf5                                   >=1.10.6
  - holoviews                              >=1.13.3
  - httpx                                  >=0.14.2
  - hvplot                                 >=0.6.0
  - hypercorn                              >=0.10.2
  - hyperopt                               >=0.2.4
  - hypothesis                             >=5.28.0
  - idna                                   >=2.10
  - invoke                                 <1.3
  - ipykernel                              >=5.3.4
  - ipyscales                              >=0.5.0
  - ipython                                >=7.18.0
  - ipywidgets                             >=7.5.1
  - isort                                  >=5.4.2
  - itsdangerous                           >=1.1.0
  - jax                                    >=0.1.75
  - jedi                                   >=0.17.2
  - jinja2                                 >=2.11.2
  - joblib                                 >=0.16.0
  - jsonschema                             >=3.2.0
  - jupyter_console                        >=6.1.0
  - jupyter-server-proxy                   >=1.5.0
  - jupyterlab                             >=2.2.6
  - jupyterlab-git                         >=0.21.1
  - keras                                  >=2.4.3
  - lightgbm                               >=2.3.1
  - line_profiler                          >=3.0.2
  - locket                                 >=0.2.0
  - lxml                                   >=4.5.2
  - markupsafe                             >=1.1.1
  - matplotlib                             >=3.3.1
  - mechanicalsoup                         >=0.12.0
  - memory_profiler                        >=0.57.0
  - mistune                                >=0.8.4
  - mkdocs                                 >=1.1.2
  - mkdocs-material                        >=5.5.9
  - mkdocs-material-extensions             >=1.0
  - mlxtend                                >=0.17.3
  - mpmath                                 >=1.1.0
  - multipledispatch                       >=0.6.0
  - murmurhash                             >=1.0.0
  - mypy                                   >=0.782
  - nbconvert                              >=5.6.1
  - nbdime                                 >=2.0.0
  - nbformat                               >=5.0.7
  - networkx                               >=2.5
  - nlopt                                  >=2.6.2
  - nltk                                   >=3.4.4
  - nodejs                                 >=14.10.1
  - notebook                               >=6.1.4
  - numba                                  >=0.51.1
  - numba::icc_rt                          >=2020.2
  - numdifftools                           >=0.9.39
  - numexpr                                >=2.7.1
  - numpydoc                               >=1.1.0
  - opencv                                 >=4.4.0
  - openpyxl                               >=3.0.5
  - opt_einsum                             >=3.3.0
  - optuna                                 >=2.1.0
  - outcome                                >=1.0.1
  - packaging                              >=20.4
  - pandas                                 >=1.1.1
  - pandoc                                 >=2.10.1
  - pandocfilters                          >=1.4.2
  - patsy                                  >=0.5.1
  - pep8                                   >=1.7.1
  - pexpect                                >=4.8.0
  - phantomjs                              >=2.1.1
  - pillow                                 >=7.2
  - plotly                                 >=4.9.0
  - plotnine                               >=0.7.1
  - pomegranate                            >=0.13.3
  - prompt_toolkit                         >=3.0.6
  - psutil                                 >=5.7.2
  - psycopg2                               >=2.8.5
  - ptvsd                                  >=4.3.2
  - py-xgboost                             >=0.90
  - pyarrow                                >=1.0.1
  - pycrypto                               >=2.6.1
  - pycurl                                 >=7.43.0.5
  - pydantic                               >=1.6.1
  - pydot                                  >=1.4.1
  - pyflakes                               >=2.2.0
  - pygments                               >=2.6.1
  - pylint                                 >=2.6.0
  - pyls-black                             >=0.4.6
  - pyls-mypy                              >=0.1.8
  - pymc3                                  >=3.9.3
  - pynndescent                            >=0.4.8
  - pyodbc                                 >=4.0.30
  - pytables                               >=3.6.1
  - pytest                                 >=6.0.1
  - pytest-cov                             >=2.10.1
  - pytest-doctestplus                     >=0.8.0
  - python-blosc                           >=1.9.1
  - python-dateutil                        >=2.8.1
  - python-language-server                 >=0.34.0
  - pytorch::pytorch                       >=1.6.0
  - pytorch::torchvision                   >=0.7
  - pytz                                   >=2020.1
  - quart                                  >=0.13.0
  - requests                               >=2.24
  - rise                                   >=5.6.1
  - rope                                   >=0.17.0
  - ruamel_yaml                            >=0.15.87
  - scikit-image                           >=0.17.2
  - scikit-optimize                        >=0.7.4
  - seaborn                                >=0.10.1
  - selenium                               >=3.141.0
  - shap                                   >=0.35.0
  - skorch                                 >=0.8.0
  - smbprotocol                            >=1.1.0
  - snowballstemmer                        >=2.0.0
  - spacy                                  >=2.3.2
  - sparse                                 >=0.11.0
  - spyder-kernels                         >=1.9.4
  - sqlacodegen                            >=2.3
  - sqlalchemy                             >=1.3.19
  - sqlalchemy-utils                       >=0.36.6
  - statsmodels                            >=0.12.0
  - stumpy                                 >=1.5.0
  - sympy                                  >=1.6.2
  - tblib                                  >=1.6.0
  - tenacity                               >=6.2.0
  - terminado                              >=0.8.3
  - theano                                 >=1.0.5
  - toolz                                  >=0.10.0
  - tpot                                   >=0.11.5
  - tqdm                                   >=4.48.2
  - traitlets                              >=5.0.3
  - trio                                   >=0.16.0
  - trio_asyncio                           >=0.11.0
  - turbodbc                               >=4.1.1
  - typing_extensions                      >=3.7.4.2
  - tzlocal                                >=2.1
  - umap-learn                             >=0.4.6
  - werkzeug                               >=1.0.1
  - wrapt                                  >=1.11.2
  - xarray                                 >=0.16.0
  - xlrd                                   >=1.2.0
  - xlsxwriter                             >=1.3.3
  - xlwt                                   >=1.3.0
  - yellowbrick                            >=1.1
  - zlib                                   >=1.2.11
  - zstd                                   >=1.4.5
```
</details>

```
 mamba env create --file https://gist.githubusercontent.com/dhirschfeld/6a56e6c7c32551e013291950ec0da020/raw/e336bac3e24b081fc7b221beacc7df5a7e849390/environment.yml
```
