### ISSUE TITLE
[micromamba] allow pip in env.yml files

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#589]
We should also add support for `pip` in environment yml files.  cc @ocefpaf

More generally, we could think about supporting arbitrary other package managers.

We could have a format where people can add a templated command line that will be used to install packages from keys, e.g.

```yml
cmds:
- pip: "pip install {pkg_name}"
- npm: "npm install {pkg_name}"
- apt: "apt install {pkg_name}"
dependencies:
- bla
- bli
- pip:
  - matplotlib
  - something
- apt:
  - kernel-headers
```

We might also want to have an installation order, so maybe evaluate the installers at the place where they appear in the dependencies list.

Also something that came up for conda's env.yml files is support for selectors for different OS, for example. In conda this is done with the # selector syntax, which I dislike because it's actually a comment. In boa we're currently working with the proposal to use a syntax like `- sel(win): win32deps`, which we could re-use here. This would also be a good opportunity to implement the selector logic in C++ so that we have it available whenever we switch to a native `boa` :)
