### ISSUE TITLE
Mamba installing packages that use different python version

### ISSUE THREAD

**Issue by zbs** [mamba-org/mamba#787]
The `mamba env create` command fails to install python 2.7-compatible libraries when running the following command
```mamba env create -f test_abstract.yml -p /dev/shm/foo/envs/test_mamba_and_twisted```
with the following `test_abstract.yml` file
```
channels:
  - pytorch                                                                                                                                                                                                                                                                                                                                    
  - conda-forge
  - defaults
  - prometeia
  - mosek
dependencies:
  - python=2.7.18
  - twisted
```

namely, it attempts to install `pyhamcrest==2.0.2`, which is compatible with python 3.5+:

```
──────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────

  _libgcc_mutex             0.1  conda_forge     conda-forge/linux-64     Cached
  _openmp_mutex             4.5  1_gnu           conda-forge/linux-64     Cached
  attrs                  20.3.0  pyhd3deb0d_0    conda-forge/noarch       Cached
  automat                20.2.0  py_0            conda-forge/noarch       Cached
  bcrypt                  3.1.7  py27h516909a_0  conda-forge/linux-64     Cached
  ca-certificates     2021.1.19  h06a4308_1      pkgs/main/linux-64       Cached
  certifi             2020.6.20  pyhd3eb1b0_3    pkgs/main/noarch         Cached
  cffi                   1.14.0  py27he30daa8_1  pkgs/main/linux-64       Cached
  constantly             15.1.0  py_0            conda-forge/noarch       Cached
  cryptography              2.8  py27h2c19f6a_2  conda-forge/linux-64     Cached
  enum34                 1.1.10  py27h8c360ce_1  conda-forge/linux-64     Cached
  hyperlink              21.0.0  pyhd3deb0d_0    conda-forge/noarch       Cached
  idna                      3.1  pyhd3deb0d_0    conda-forge/noarch       Cached
  incremental            17.5.0  py_0            conda-forge/noarch       Cached
  ipaddress              1.0.23  py_0            conda-forge/noarch       Cached
  libffi                    3.3  h58526e2_2      conda-forge/linux-64     Cached
  libgcc-ng               9.3.0  h2828fa1_18     conda-forge/linux-64     Cached
  libgomp                 9.3.0  h2828fa1_18     conda-forge/linux-64     Cached
  libstdcxx-ng            9.3.0  h6de172a_18     conda-forge/linux-64     Cached
  ncurses                   6.2  h58526e2_4      conda-forge/linux-64     Cached
  openssl           1.1.1.post1  h14c3975_0      prometeia/linux-64       Cached
  pip                    20.1.1  pyh9f0ad1d_0    conda-forge/noarch       Cached
  pyasn1                  0.4.8  py_0            conda-forge/noarch       Cached
  pyasn1-modules          0.2.8  py_0            pkgs/main/noarch         Cached
  pycparser                2.20  pyh9f0ad1d_2    conda-forge/noarch       Cached
  pyhamcrest              2.0.2  pyhd3eb1b0_2    pkgs/main/noarch         Cached
  pyopenssl              20.0.1  pyhd3eb1b0_1    pkgs/main/noarch         Cached
  python                 2.7.18  h15b4118_1      pkgs/main/linux-64       Cached
  python_abi                2.7  1_cp27mu        conda-forge/linux-64     Cached
  readline                  8.1  h27cfd23_0      pkgs/main/linux-64       Cached
  service_identity       18.1.0  py_0            conda-forge/noarch       Cached
  setuptools             44.0.0  py27_0          conda-forge/linux-64     Cached
  six                    1.15.0  pyh9f0ad1d_0    conda-forge/noarch       Cached
  sqlite                 3.35.2  hdfb4753_0      pkgs/main/linux-64       Cached
  tk                     8.6.10  hed695b0_1      conda-forge/linux-64     Cached
  twisted               19.10.0  py27h516909a_0  conda-forge/linux-64     Cached
  wheel                  0.36.2  pyhd3deb0d_0    conda-forge/noarch       Cached
  zlib                   1.2.11  h516909a_1010   conda-forge/linux-64     Cached
  zope.interface          5.0.0  py27hdf8410d_0  conda-forge/linux-64     Cached
```

This is strange because it acknowledges the constraint of python==2.7:

```
  Looking for: ['python=2.7.18', 'twisted']                                                                                                                                                                                                                                                                                                      
```

I suspect this is because the environment running mamba uses python 3.5. But if so, that seems like a glaring bug. I compared with regular vanilla conda, and seems to avoid this issue.

**Comment by tholam** [comment]
The issue seems to be that the pyhamcrest package in the main anaconda channel had a new release 7 days ago that relaxed the requirements.

```
# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Sun Mar 14 19:03:51 2021
# ------------------------------------------------

package:
  name: pyhamcrest
  version: 2.0.2
source:
  fn: PyHamcrest-2.0.2.tar.gz
  md5: 7a086f0b067f8d38958ec32f054559b4
  url: https://pypi.python.org/packages/source/P/PyHamcrest/PyHamcrest-2.0.2.tar.gz
build:
  noarch: python
  number: '2'
  script: python -m pip install --no-deps --ignore-installed .
  string: pyhd3eb1b0_2
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_1
    - certifi 2020.12.5 py36h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20191231 h14c3975_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1j h27cfd23_0
    - pip 21.0.1 py36h06a4308_0
    - python 3.6.13 hdb3f193_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py36h06a4308_0
    - sqlite 3.33.0 h62c20be_0
    - tk 8.6.10 hbc83047_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python
    - six
test:
  imports:
    - hamcrest
    - hamcrest.core
    - hamcrest.core.core
    - hamcrest.core.helpers
    - hamcrest.library
    - hamcrest.library.collection
    - hamcrest.library.integration
    - hamcrest.library.number
    - hamcrest.library.object
    - hamcrest.library.text
about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD 3-Clause
  summary: Hamcrest framework for matcher objects
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - duncanwp
    - stuertz
```
