### ISSUE TITLE
'update' with an environment file inconsistent with conda

### ISSUE THREAD

**Issue by ScottWales** [mamba-org/mamba#854]
Running an update using an environment file does not work as expected to update installed packages, using both micromamba and mamba

With a basic environment file:
```yaml
# env-1.yml
channels:
- conda-forge
dependencies:
- python>=3.8
- numpy=1.18.1
- scipy
```
running `micromamba create -p $PWD/env -f env-1.yml` gives an envionment with python 3.8.8 and numpy 1.18.1, as expected.

Now I'd like to update scipy to its latest version, so I run `micromamba update -p $PWD/env -f env-1.yml`. This now installs python 3.9.2 and numpy 1.20.2, breaking the numpy constraint in the environment file.

If on the other hand I use mamba, and run `mamba env create --prefix $PWD/env -f env-1.yml` to get python 3.8.8 and numpy 1.18.1 again, then do an update with `mamba env update --prefix $PWD/env -f env-1.yml` nothing happens as expected - the  constraints are already satisfied. Now if I change the environment file itself to remove the pin on numpy:
```yaml
# env-2.yml
channels:
- conda-forge
dependencies:
- python>=3.8
- numpy
- scipy
```
and run `mamba env update --prefix $PWD/env -f env-2.yml` to get the latest numpy (presumably 1.20.2), mamba reports `All requested packages already installed`, and doesn't update numpy.

Using conda directly with `conda env update --prefix $PWD/env -f env-2.yml` updates numpy to 1.20.2 as expected.

**Expected Behaviour**:

After creating an environment with `env-1.yml`:
* Running an update with `env-1.yml` keeps numpy pinned to 1.18.1
* Running an update with `env-2.yml` removes the numpy pin, installing some future version e.g. 1.20.2
